export const fieldingStats = [
  // Giants
  {
    playerId: "giants-1",
    seasonYear: 2025,
    position: "一塁手",
    games: 130,
    putouts: 1089,
    assists: 82,
    errors: 7,
    doublePlays: 98,
    fieldingPct: 0.994,
  },
  {
    playerId: "giants-2",
    seasonYear: 2025,
    position: "遊撃手",
    games: 118,
    putouts: 178,
    assists: 362,
    errors: 11,
    doublePlays: 74,
    fieldingPct: 0.980,
  },
  {
    playerId: "giants-3",
    seasonYear: 2025,
    position: "外野手",
    games: 122,
    putouts: 234,
    assists: 5,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.992,
  },
  {
    playerId: "giants-4",
    seasonYear: 2025,
    position: "投手",
    games: 25,
    putouts: 18,
    assists: 34,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.981,
  },
  {
    playerId: "giants-5",
    seasonYear: 2025,
    position: "投手",
    games: 22,
    putouts: 14,
    assists: 28,
    errors: 0,
    doublePlays: 1,
    fieldingPct: 1.000,
  },
  {
    playerId: "giants-6",
    seasonYear: 2025,
    position: "投手",
    games: 20,
    putouts: 12,
    assists: 23,
    errors: 1,
    doublePlays: 0,
    fieldingPct: 0.972,
  },

  // Tigers
  {
    playerId: "tigers-1",
    seasonYear: 2025,
    position: "外野手",
    games: 125,
    putouts: 198,
    assists: 7,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.995,
  },
  {
    playerId: "tigers-2",
    seasonYear: 2025,
    position: "外野手",
    games: 140,
    putouts: 287,
    assists: 8,
    errors: 3,
    doublePlays: 1,
    fieldingPct: 0.990,
  },
  {
    playerId: "tigers-3",
    seasonYear: 2025,
    position: "遊撃手",
    games: 132,
    putouts: 215,
    assists: 398,
    errors: 14,
    doublePlays: 88,
    fieldingPct: 0.978,
  },
  {
    playerId: "tigers-4",
    seasonYear: 2025,
    position: "投手",
    games: 23,
    putouts: 16,
    assists: 31,
    errors: 2,
    doublePlays: 3,
    fieldingPct: 0.959,
  },
  {
    playerId: "tigers-5",
    seasonYear: 2025,
    position: "投手",
    games: 21,
    putouts: 13,
    assists: 27,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.976,
  },
  {
    playerId: "tigers-6",
    seasonYear: 2025,
    position: "投手",
    games: 19,
    putouts: 11,
    assists: 22,
    errors: 0,
    doublePlays: 1,
    fieldingPct: 1.000,
  },

  // BayStars (2025年)
  {
    playerId: "baystars-1",
    seasonYear: 2025,
    position: "二塁手",
    games: 90,
    putouts: 162,
    assists: 244,
    errors: 6,
    doublePlays: 52,
    fieldingPct: 0.985,
  },
  {
    playerId: "baystars-2",
    seasonYear: 2025,
    position: "外野手",
    games: 128,
    putouts: 218,
    assists: 5,
    errors: 2,
    doublePlays: 0,
    fieldingPct: 0.991,
  },
  {
    playerId: "baystars-3",
    seasonYear: 2025,
    position: "捕手",
    games: 100,
    putouts: 648,
    assists: 50,
    errors: 5,
    doublePlays: 8,
    fieldingPct: 0.993,
  },
  {
    playerId: "baystars-4",
    seasonYear: 2025,
    position: "投手",
    games: 26,
    putouts: 18,
    assists: 32,
    errors: 1,
    doublePlays: 3,
    fieldingPct: 0.980,
  },
  {
    playerId: "baystars-5",
    seasonYear: 2025,
    position: "三塁手",
    games: 120,
    putouts: 78,
    assists: 218,
    errors: 7,
    doublePlays: 22,
    fieldingPct: 0.977,
  },
  {
    playerId: "baystars-6",
    seasonYear: 2025,
    position: "外野手",
    games: 108,
    putouts: 168,
    assists: 3,
    errors: 2,
    doublePlays: 0,
    fieldingPct: 0.988,
  },

  // Carp
  {
    playerId: "carp-1",
    seasonYear: 2025,
    position: "外野手",
    games: 138,
    putouts: 271,
    assists: 6,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.996,
  },
  {
    playerId: "carp-2",
    seasonYear: 2025,
    position: "外野手",
    games: 130,
    putouts: 243,
    assists: 9,
    errors: 3,
    doublePlays: 1,
    fieldingPct: 0.988,
  },
  {
    playerId: "carp-3",
    seasonYear: 2025,
    position: "外野手",
    games: 119,
    putouts: 187,
    assists: 3,
    errors: 2,
    doublePlays: 0,
    fieldingPct: 0.990,
  },
  {
    playerId: "carp-4",
    seasonYear: 2025,
    position: "投手",
    games: 24,
    putouts: 17,
    assists: 33,
    errors: 1,
    doublePlays: 3,
    fieldingPct: 0.980,
  },
  {
    playerId: "carp-5",
    seasonYear: 2025,
    position: "投手",
    games: 25,
    putouts: 19,
    assists: 36,
    errors: 0,
    doublePlays: 2,
    fieldingPct: 1.000,
  },
  {
    playerId: "carp-6",
    seasonYear: 2025,
    position: "投手",
    games: 22,
    putouts: 15,
    assists: 29,
    errors: 1,
    doublePlays: 1,
    fieldingPct: 0.978,
  },

  // Dragons
  {
    playerId: "dragons-1",
    seasonYear: 2025,
    position: "外野手",
    games: 143,
    putouts: 295,
    assists: 7,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.993,
  },
  {
    playerId: "dragons-2",
    seasonYear: 2025,
    position: "外野手",
    games: 136,
    putouts: 258,
    assists: 5,
    errors: 1,
    doublePlays: 0,
    fieldingPct: 0.996,
  },
  {
    playerId: "dragons-3",
    seasonYear: 2025,
    position: "三塁手",
    games: 124,
    putouts: 143,
    assists: 289,
    errors: 16,
    doublePlays: 67,
    fieldingPct: 0.964,
  },
  {
    playerId: "dragons-4",
    seasonYear: 2025,
    position: "投手",
    games: 27,
    putouts: 22,
    assists: 40,
    errors: 2,
    doublePlays: 3,
    fieldingPct: 0.969,
  },
  {
    playerId: "dragons-5",
    seasonYear: 2025,
    position: "投手",
    games: 24,
    putouts: 16,
    assists: 30,
    errors: 0,
    doublePlays: 2,
    fieldingPct: 1.000,
  },
  {
    playerId: "dragons-6",
    seasonYear: 2025,
    position: "投手",
    games: 20,
    putouts: 11,
    assists: 21,
    errors: 1,
    doublePlays: 0,
    fieldingPct: 0.970,
  },

  // Swallows
  {
    playerId: "swallows-1",
    seasonYear: 2025,
    position: "三塁手",
    games: 137,
    putouts: 121,
    assists: 312,
    errors: 18,
    doublePlays: 59,
    fieldingPct: 0.960,
  },
  {
    playerId: "swallows-2",
    seasonYear: 2025,
    position: "外野手",
    games: 116,
    putouts: 203,
    assists: 4,
    errors: 3,
    doublePlays: 1,
    fieldingPct: 0.986,
  },
  {
    playerId: "swallows-3",
    seasonYear: 2025,
    position: "二塁手",
    games: 129,
    putouts: 232,
    assists: 355,
    errors: 10,
    doublePlays: 79,
    fieldingPct: 0.983,
  },
  {
    playerId: "swallows-4",
    seasonYear: 2025,
    position: "投手",
    games: 23,
    putouts: 14,
    assists: 26,
    errors: 1,
    doublePlays: 1,
    fieldingPct: 0.976,
  },
  {
    playerId: "swallows-5",
    seasonYear: 2025,
    position: "投手",
    games: 16,
    putouts: 10,
    assists: 19,
    errors: 0,
    doublePlays: 0,
    fieldingPct: 1.000,
  },
  {
    playerId: "swallows-6",
    seasonYear: 2025,
    position: "投手",
    games: 22,
    putouts: 15,
    assists: 32,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.979,
  },

  // Hawks
  {
    playerId: "hawks-1",
    seasonYear: 2025,
    position: "外野手",
    games: 141,
    putouts: 276,
    assists: 9,
    errors: 2,
    doublePlays: 2,
    fieldingPct: 0.993,
  },
  {
    playerId: "hawks-2",
    seasonYear: 2025,
    position: "外野手",
    games: 134,
    putouts: 255,
    assists: 6,
    errors: 3,
    doublePlays: 1,
    fieldingPct: 0.989,
  },
  {
    playerId: "hawks-3",
    seasonYear: 2025,
    position: "捕手",
    games: 120,
    putouts: 812,
    assists: 65,
    errors: 5,
    doublePlays: 11,
    fieldingPct: 0.994,
  },
  {
    playerId: "hawks-4",
    seasonYear: 2025,
    position: "投手",
    games: 26,
    putouts: 20,
    assists: 37,
    errors: 0,
    doublePlays: 3,
    fieldingPct: 1.000,
  },
  {
    playerId: "hawks-5",
    seasonYear: 2025,
    position: "投手",
    games: 24,
    putouts: 17,
    assists: 31,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.980,
  },
  {
    playerId: "hawks-6",
    seasonYear: 2025,
    position: "投手",
    games: 21,
    putouts: 14,
    assists: 28,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.955,
  },

  // Marines
  {
    playerId: "marines-1",
    seasonYear: 2025,
    position: "外野手",
    games: 127,
    putouts: 222,
    assists: 5,
    errors: 2,
    doublePlays: 0,
    fieldingPct: 0.991,
  },
  {
    playerId: "marines-2",
    seasonYear: 2025,
    position: "二塁手",
    games: 133,
    putouts: 265,
    assists: 391,
    errors: 12,
    doublePlays: 86,
    fieldingPct: 0.982,
  },
  {
    playerId: "marines-3",
    seasonYear: 2025,
    position: "一塁手",
    games: 128,
    putouts: 1043,
    assists: 75,
    errors: 5,
    doublePlays: 103,
    fieldingPct: 0.996,
  },
  {
    playerId: "marines-4",
    seasonYear: 2025,
    position: "投手",
    games: 25,
    putouts: 18,
    assists: 35,
    errors: 1,
    doublePlays: 4,
    fieldingPct: 0.981,
  },
  {
    playerId: "marines-5",
    seasonYear: 2025,
    position: "投手",
    games: 23,
    putouts: 16,
    assists: 30,
    errors: 0,
    doublePlays: 2,
    fieldingPct: 1.000,
  },
  {
    playerId: "marines-6",
    seasonYear: 2025,
    position: "投手",
    games: 19,
    putouts: 12,
    assists: 24,
    errors: 1,
    doublePlays: 1,
    fieldingPct: 0.973,
  },

  // Eagles
  {
    playerId: "eagles-1",
    seasonYear: 2025,
    position: "二塁手",
    games: 131,
    putouts: 241,
    assists: 367,
    errors: 13,
    doublePlays: 77,
    fieldingPct: 0.979,
  },
  {
    playerId: "eagles-2",
    seasonYear: 2025,
    position: "外野手",
    games: 139,
    putouts: 263,
    assists: 7,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.993,
  },
  {
    playerId: "eagles-3",
    seasonYear: 2025,
    position: "外野手",
    games: 123,
    putouts: 197,
    assists: 4,
    errors: 3,
    doublePlays: 0,
    fieldingPct: 0.985,
  },
  {
    playerId: "eagles-4",
    seasonYear: 2025,
    position: "投手",
    games: 27,
    putouts: 23,
    assists: 42,
    errors: 2,
    doublePlays: 5,
    fieldingPct: 0.970,
  },
  {
    playerId: "eagles-5",
    seasonYear: 2025,
    position: "投手",
    games: 22,
    putouts: 15,
    assists: 27,
    errors: 0,
    doublePlays: 2,
    fieldingPct: 1.000,
  },
  {
    playerId: "eagles-6",
    seasonYear: 2025,
    position: "投手",
    games: 20,
    putouts: 13,
    assists: 26,
    errors: 1,
    doublePlays: 1,
    fieldingPct: 0.975,
  },

  // Buffaloes
  {
    playerId: "buffaloes-1",
    seasonYear: 2025,
    position: "捕手",
    games: 118,
    putouts: 768,
    assists: 54,
    errors: 7,
    doublePlays: 8,
    fieldingPct: 0.991,
  },
  {
    playerId: "buffaloes-2",
    seasonYear: 2025,
    position: "外野手",
    games: 132,
    putouts: 248,
    assists: 6,
    errors: 4,
    doublePlays: 1,
    fieldingPct: 0.984,
  },
  {
    playerId: "buffaloes-3",
    seasonYear: 2025,
    position: "二塁手",
    games: 126,
    putouts: 218,
    assists: 333,
    errors: 15,
    doublePlays: 71,
    fieldingPct: 0.973,
  },
  {
    playerId: "buffaloes-4",
    seasonYear: 2025,
    position: "投手",
    games: 26,
    putouts: 19,
    assists: 36,
    errors: 1,
    doublePlays: 3,
    fieldingPct: 0.982,
  },
  {
    playerId: "buffaloes-5",
    seasonYear: 2025,
    position: "投手",
    games: 24,
    putouts: 16,
    assists: 29,
    errors: 0,
    doublePlays: 2,
    fieldingPct: 1.000,
  },
  {
    playerId: "buffaloes-6",
    seasonYear: 2025,
    position: "投手",
    games: 21,
    putouts: 14,
    assists: 25,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.951,
  },

  // Lions
  {
    playerId: "lions-1",
    seasonYear: 2025,
    position: "遊撃手",
    games: 136,
    putouts: 209,
    assists: 412,
    errors: 17,
    doublePlays: 91,
    fieldingPct: 0.973,
  },
  {
    playerId: "lions-2",
    seasonYear: 2025,
    position: "二塁手",
    games: 129,
    putouts: 237,
    assists: 349,
    errors: 11,
    doublePlays: 76,
    fieldingPct: 0.981,
  },
  {
    playerId: "lions-3",
    seasonYear: 2025,
    position: "一塁手",
    games: 133,
    putouts: 1127,
    assists: 88,
    errors: 9,
    doublePlays: 112,
    fieldingPct: 0.993,
  },
  {
    playerId: "lions-4",
    seasonYear: 2025,
    position: "投手",
    games: 24,
    putouts: 17,
    assists: 33,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.980,
  },
  {
    playerId: "lions-5",
    seasonYear: 2025,
    position: "投手",
    games: 22,
    putouts: 15,
    assists: 28,
    errors: 0,
    doublePlays: 3,
    fieldingPct: 1.000,
  },
  {
    playerId: "lions-6",
    seasonYear: 2025,
    position: "投手",
    games: 20,
    putouts: 12,
    assists: 22,
    errors: 1,
    doublePlays: 1,
    fieldingPct: 0.971,
  },

  // Fighters
  {
    playerId: "fighters-1",
    seasonYear: 2025,
    position: "外野手",
    games: 138,
    putouts: 266,
    assists: 8,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.993,
  },
  {
    playerId: "fighters-2",
    seasonYear: 2025,
    position: "外野手",
    games: 131,
    putouts: 239,
    assists: 5,
    errors: 3,
    doublePlays: 0,
    fieldingPct: 0.988,
  },
  {
    playerId: "fighters-3",
    seasonYear: 2025,
    position: "捕手",
    games: 122,
    putouts: 851,
    assists: 71,
    errors: 4,
    doublePlays: 13,
    fieldingPct: 0.996,
  },
  {
    playerId: "fighters-4",
    seasonYear: 2025,
    position: "投手",
    games: 25,
    putouts: 19,
    assists: 38,
    errors: 0,
    doublePlays: 4,
    fieldingPct: 1.000,
  },
  {
    playerId: "fighters-5",
    seasonYear: 2025,
    position: "投手",
    games: 23,
    putouts: 16,
    assists: 31,
    errors: 1,
    doublePlays: 2,
    fieldingPct: 0.979,
  },
  {
    playerId: "fighters-6",
    seasonYear: 2025,
    position: "投手",
    games: 21,
    putouts: 13,
    assists: 26,
    errors: 2,
    doublePlays: 1,
    fieldingPct: 0.951,
  },
];
