export const games: {
  seasonYear: number;
  date: string;
  homeTeamId: string;
  awayTeamId: string;
  homeScore: number;
  awayScore: number;
  stadiumId: string;
  attendance: number;
  duration: number;
  gameType: string;
}[] = [
  // --- April ---
  {
    seasonYear: 2024,
    date: "2024-04-01",
    homeTeamId: "giants",
    awayTeamId: "swallows",
    homeScore: 5,
    awayScore: 2,
    stadiumId: "tokyo-dome",
    attendance: 42800,
    duration: 188,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-02",
    homeTeamId: "tigers",
    awayTeamId: "carp",
    homeScore: 3,
    awayScore: 1,
    stadiumId: "hanshin-koshien",
    attendance: 45000,
    duration: 175,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-03",
    homeTeamId: "baystars",
    awayTeamId: "dragons",
    homeScore: 4,
    awayScore: 4,
    stadiumId: "yokohama-stadium",
    attendance: 31500,
    duration: 200,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-05",
    homeTeamId: "hawks",
    awayTeamId: "marines",
    homeScore: 7,
    awayScore: 3,
    stadiumId: "fukuoka-paypay",
    attendance: 38200,
    duration: 192,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-06",
    homeTeamId: "eagles",
    awayTeamId: "buffaloes",
    homeScore: 2,
    awayScore: 5,
    stadiumId: "miyagi-baseball",
    attendance: 21000,
    duration: 185,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-07",
    homeTeamId: "lions",
    awayTeamId: "fighters",
    homeScore: 1,
    awayScore: 3,
    stadiumId: "belluna-dome",
    attendance: 19500,
    duration: 170,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-12",
    homeTeamId: "carp",
    awayTeamId: "giants",
    homeScore: 6,
    awayScore: 2,
    stadiumId: "mazda-stadium",
    attendance: 30800,
    duration: 183,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-04-13",
    homeTeamId: "dragons",
    awayTeamId: "tigers",
    homeScore: 0,
    awayScore: 4,
    stadiumId: "bantelink-nagoya",
    attendance: 34000,
    duration: 162,
    gameType: "公式戦",
  },

  // --- May ---
  {
    seasonYear: 2024,
    date: "2024-05-03",
    homeTeamId: "tigers",
    awayTeamId: "baystars",
    homeScore: 8,
    awayScore: 5,
    stadiumId: "hanshin-koshien",
    attendance: 46200,
    duration: 210,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-04",
    homeTeamId: "swallows",
    awayTeamId: "carp",
    homeScore: 2,
    awayScore: 2,
    stadiumId: "jingu-stadium",
    attendance: 28500,
    duration: 195,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-05",
    homeTeamId: "marines",
    awayTeamId: "eagles",
    homeScore: 5,
    awayScore: 1,
    stadiumId: "zozo-marine",
    attendance: 27400,
    duration: 178,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-10",
    homeTeamId: "buffaloes",
    awayTeamId: "hawks",
    homeScore: 3,
    awayScore: 6,
    stadiumId: "kyocera-dome",
    attendance: 33700,
    duration: 197,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-17",
    homeTeamId: "fighters",
    awayTeamId: "lions",
    homeScore: 4,
    awayScore: 2,
    stadiumId: "escon-field",
    attendance: 32000,
    duration: 180,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-24",
    homeTeamId: "giants",
    awayTeamId: "carp",
    homeScore: 3,
    awayScore: 4,
    stadiumId: "tokyo-dome",
    attendance: 43500,
    duration: 191,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-05-31",
    homeTeamId: "hawks",
    awayTeamId: "eagles",
    homeScore: 9,
    awayScore: 2,
    stadiumId: "fukuoka-paypay",
    attendance: 39100,
    duration: 205,
    gameType: "公式戦",
  },

  // --- June ---
  {
    seasonYear: 2024,
    date: "2024-06-07",
    homeTeamId: "baystars",
    awayTeamId: "swallows",
    homeScore: 6,
    awayScore: 3,
    stadiumId: "yokohama-stadium",
    attendance: 32800,
    duration: 187,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-06-14",
    homeTeamId: "marines",
    awayTeamId: "buffaloes",
    homeScore: 2,
    awayScore: 2,
    stadiumId: "zozo-marine",
    attendance: 25600,
    duration: 193,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-06-21",
    homeTeamId: "carp",
    awayTeamId: "swallows",
    homeScore: 5,
    awayScore: 0,
    stadiumId: "mazda-stadium",
    attendance: 29300,
    duration: 165,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-06-28",
    homeTeamId: "lions",
    awayTeamId: "marines",
    homeScore: 3,
    awayScore: 7,
    stadiumId: "belluna-dome",
    attendance: 18700,
    duration: 202,
    gameType: "公式戦",
  },

  // --- July ---
  {
    seasonYear: 2024,
    date: "2024-07-05",
    homeTeamId: "tigers",
    awayTeamId: "giants",
    homeScore: 2,
    awayScore: 1,
    stadiumId: "hanshin-koshien",
    attendance: 47000,
    duration: 179,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-07-06",
    homeTeamId: "dragons",
    awayTeamId: "baystars",
    homeScore: 4,
    awayScore: 3,
    stadiumId: "bantelink-nagoya",
    attendance: 35200,
    duration: 198,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-07-13",
    homeTeamId: "eagles",
    awayTeamId: "fighters",
    homeScore: 6,
    awayScore: 4,
    stadiumId: "miyagi-baseball",
    attendance: 22100,
    duration: 190,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-07-19",
    homeTeamId: "hawks",
    awayTeamId: "lions",
    homeScore: 10,
    awayScore: 3,
    stadiumId: "fukuoka-paypay",
    attendance: 40000,
    duration: 208,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-07-26",
    homeTeamId: "swallows",
    awayTeamId: "giants",
    homeScore: 1,
    awayScore: 5,
    stadiumId: "jingu-stadium",
    attendance: 29700,
    duration: 173,
    gameType: "公式戦",
  },

  // --- August ---
  {
    seasonYear: 2024,
    date: "2024-08-02",
    homeTeamId: "buffaloes",
    awayTeamId: "fighters",
    homeScore: 5,
    awayScore: 2,
    stadiumId: "kyocera-dome",
    attendance: 31400,
    duration: 181,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-08-09",
    homeTeamId: "baystars",
    awayTeamId: "carp",
    homeScore: 3,
    awayScore: 3,
    stadiumId: "yokohama-stadium",
    attendance: 34100,
    duration: 196,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-08-16",
    homeTeamId: "marines",
    awayTeamId: "hawks",
    homeScore: 4,
    awayScore: 6,
    stadiumId: "zozo-marine",
    attendance: 28900,
    duration: 203,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-08-23",
    homeTeamId: "fighters",
    awayTeamId: "eagles",
    homeScore: 2,
    awayScore: 4,
    stadiumId: "escon-field",
    attendance: 33500,
    duration: 186,
    gameType: "公式戦",
  },

  // --- September ---
  {
    seasonYear: 2024,
    date: "2024-09-06",
    homeTeamId: "giants",
    awayTeamId: "dragons",
    homeScore: 7,
    awayScore: 1,
    stadiumId: "tokyo-dome",
    attendance: 44600,
    duration: 194,
    gameType: "公式戦",
  },
  {
    seasonYear: 2024,
    date: "2024-09-20",
    homeTeamId: "tigers",
    awayTeamId: "swallows",
    homeScore: 4,
    awayScore: 1,
    stadiumId: "hanshin-koshien",
    attendance: 46800,
    duration: 176,
    gameType: "公式戦",
  },
];
