export const pitchingStatsPacific: {
  playerId: string;
  seasonYear: number;
  games: number;
  starts: number;
  completeGames: number;
  shutouts: number;
  wins: number;
  losses: number;
  saves: number;
  holds: number;
  blownSaves: number;
  inningsPitched: number;
  hitsAllowed: number;
  runsAllowed: number;
  earnedRuns: number;
  walksAllowed: number;
  intentionalWalks: number;
  hitBatters: number;
  strikeouts: number;
  homeRunsAllowed: number;
  era: number;
  whip: number;
  kPer9: number;
  bbPer9: number;
  qualityStarts: number;
}[] = [
  // --- Fukuoka SoftBank Hawks ---
  {
    // 有原航平
    playerId: "hawks-4",
    seasonYear: 2025,
    games: 25,
    starts: 25,
    completeGames: 4,
    shutouts: 2,
    wins: 14,
    losses: 5,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 173.0,
    hitsAllowed: 148,
    runsAllowed: 46,
    earnedRuns: 42,
    walksAllowed: 42,
    intentionalWalks: 3,
    hitBatters: 4,
    strikeouts: 182,
    homeRunsAllowed: 12,
    era: 2.18,
    whip: 1.10,
    kPer9: 9.5,
    bbPer9: 2.2,
    qualityStarts: 18,
  },
  {
    // 石川柊太
    playerId: "hawks-5",
    seasonYear: 2025,
    games: 26,
    starts: 26,
    completeGames: 2,
    shutouts: 1,
    wins: 11,
    losses: 7,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 158.0,
    hitsAllowed: 145,
    runsAllowed: 58,
    earnedRuns: 52,
    walksAllowed: 48,
    intentionalWalks: 4,
    hitBatters: 5,
    strikeouts: 142,
    homeRunsAllowed: 14,
    era: 2.96,
    whip: 1.22,
    kPer9: 8.1,
    bbPer9: 2.7,
    qualityStarts: 15,
  },
  {
    // 松本裕樹
    playerId: "hawks-6",
    seasonYear: 2025,
    games: 58,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 4,
    losses: 3,
    saves: 28,
    holds: 0,
    blownSaves: 4,
    inningsPitched: 68.0,
    hitsAllowed: 55,
    runsAllowed: 20,
    earnedRuns: 18,
    walksAllowed: 22,
    intentionalWalks: 5,
    hitBatters: 2,
    strikeouts: 72,
    homeRunsAllowed: 4,
    era: 2.38,
    whip: 1.13,
    kPer9: 9.5,
    bbPer9: 2.9,
    qualityStarts: 0,
  },

  // --- Chiba Lotte Marines ---
  {
    // 佐々木朗希
    playerId: "marines-4",
    seasonYear: 2025,
    games: 22,
    starts: 22,
    completeGames: 5,
    shutouts: 3,
    wins: 10,
    losses: 6,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 141.2,
    hitsAllowed: 100,
    runsAllowed: 28,
    earnedRuns: 26,
    walksAllowed: 28,
    intentionalWalks: 1,
    hitBatters: 3,
    strikeouts: 196,
    homeRunsAllowed: 6,
    era: 1.65,
    whip: 0.90,
    kPer9: 12.5,
    bbPer9: 1.8,
    qualityStarts: 18,
  },
  {
    // 小島和哉
    playerId: "marines-5",
    seasonYear: 2025,
    games: 24,
    starts: 24,
    completeGames: 1,
    shutouts: 0,
    wins: 9,
    losses: 8,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 138.0,
    hitsAllowed: 130,
    runsAllowed: 48,
    earnedRuns: 44,
    walksAllowed: 46,
    intentionalWalks: 3,
    hitBatters: 4,
    strikeouts: 118,
    homeRunsAllowed: 10,
    era: 2.87,
    whip: 1.28,
    kPer9: 7.7,
    bbPer9: 3.0,
    qualityStarts: 13,
  },
  {
    // 益田直也
    playerId: "marines-6",
    seasonYear: 2025,
    games: 55,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 3,
    losses: 4,
    saves: 24,
    holds: 0,
    blownSaves: 5,
    inningsPitched: 62.0,
    hitsAllowed: 48,
    runsAllowed: 18,
    earnedRuns: 16,
    walksAllowed: 20,
    intentionalWalks: 4,
    hitBatters: 2,
    strikeouts: 66,
    homeRunsAllowed: 3,
    era: 2.32,
    whip: 1.10,
    kPer9: 9.6,
    bbPer9: 2.9,
    qualityStarts: 0,
  },

  // --- Tohoku Rakuten Eagles ---
  {
    // 田中将大
    playerId: "eagles-4",
    seasonYear: 2025,
    games: 23,
    starts: 23,
    completeGames: 2,
    shutouts: 0,
    wins: 10,
    losses: 9,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 158.2,
    hitsAllowed: 157,
    runsAllowed: 60,
    earnedRuns: 55,
    walksAllowed: 44,
    intentionalWalks: 4,
    hitBatters: 5,
    strikeouts: 134,
    homeRunsAllowed: 16,
    era: 3.12,
    whip: 1.27,
    kPer9: 7.6,
    bbPer9: 2.5,
    qualityStarts: 12,
  },
  {
    // 岸孝之
    playerId: "eagles-5",
    seasonYear: 2025,
    games: 22,
    starts: 22,
    completeGames: 1,
    shutouts: 0,
    wins: 7,
    losses: 9,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 132.0,
    hitsAllowed: 136,
    runsAllowed: 56,
    earnedRuns: 52,
    walksAllowed: 50,
    intentionalWalks: 5,
    hitBatters: 4,
    strikeouts: 108,
    homeRunsAllowed: 14,
    era: 3.55,
    whip: 1.41,
    kPer9: 7.4,
    bbPer9: 3.4,
    qualityStarts: 10,
  },
  {
    // 則本昂大
    playerId: "eagles-6",
    seasonYear: 2025,
    games: 52,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 3,
    losses: 3,
    saves: 5,
    holds: 22,
    blownSaves: 3,
    inningsPitched: 58.0,
    hitsAllowed: 50,
    runsAllowed: 20,
    earnedRuns: 18,
    walksAllowed: 18,
    intentionalWalks: 3,
    hitBatters: 2,
    strikeouts: 56,
    homeRunsAllowed: 4,
    era: 2.79,
    whip: 1.17,
    kPer9: 8.7,
    bbPer9: 2.8,
    qualityStarts: 0,
  },

  // --- Orix Buffaloes ---
  {
    // 山下舜平大
    playerId: "buffaloes-4",
    seasonYear: 2025,
    games: 26,
    starts: 26,
    completeGames: 5,
    shutouts: 2,
    wins: 16,
    losses: 4,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 177.0,
    hitsAllowed: 130,
    runsAllowed: 42,
    earnedRuns: 39,
    walksAllowed: 36,
    intentionalWalks: 2,
    hitBatters: 4,
    strikeouts: 215,
    homeRunsAllowed: 9,
    era: 1.98,
    whip: 0.94,
    kPer9: 10.9,
    bbPer9: 1.8,
    qualityStarts: 21,
  },
  {
    // 宮城大弥
    playerId: "buffaloes-5",
    seasonYear: 2025,
    games: 25,
    starts: 25,
    completeGames: 2,
    shutouts: 1,
    wins: 10,
    losses: 7,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 148.0,
    hitsAllowed: 138,
    runsAllowed: 52,
    earnedRuns: 48,
    walksAllowed: 42,
    intentionalWalks: 3,
    hitBatters: 5,
    strikeouts: 128,
    homeRunsAllowed: 12,
    era: 2.92,
    whip: 1.22,
    kPer9: 7.8,
    bbPer9: 2.6,
    qualityStarts: 14,
  },
  {
    // ワゲスパック
    playerId: "buffaloes-6",
    seasonYear: 2025,
    games: 60,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 4,
    losses: 2,
    saves: 32,
    holds: 0,
    blownSaves: 5,
    inningsPitched: 72.0,
    hitsAllowed: 52,
    runsAllowed: 18,
    earnedRuns: 16,
    walksAllowed: 18,
    intentionalWalks: 3,
    hitBatters: 1,
    strikeouts: 80,
    homeRunsAllowed: 3,
    era: 2.00,
    whip: 0.97,
    kPer9: 10.0,
    bbPer9: 2.2,
    qualityStarts: 0,
  },

  // --- Saitama Seibu Lions ---
  {
    // 髙橋光成
    playerId: "lions-4",
    seasonYear: 2025,
    games: 25,
    starts: 25,
    completeGames: 1,
    shutouts: 0,
    wins: 8,
    losses: 10,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 145.0,
    hitsAllowed: 148,
    runsAllowed: 56,
    earnedRuns: 52,
    walksAllowed: 50,
    intentionalWalks: 4,
    hitBatters: 5,
    strikeouts: 122,
    homeRunsAllowed: 14,
    era: 3.23,
    whip: 1.37,
    kPer9: 7.6,
    bbPer9: 3.1,
    qualityStarts: 11,
  },
  {
    // 今井達也
    playerId: "lions-5",
    seasonYear: 2025,
    games: 23,
    starts: 23,
    completeGames: 1,
    shutouts: 0,
    wins: 7,
    losses: 9,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 128.0,
    hitsAllowed: 135,
    runsAllowed: 52,
    earnedRuns: 48,
    walksAllowed: 44,
    intentionalWalks: 4,
    hitBatters: 4,
    strikeouts: 104,
    homeRunsAllowed: 13,
    era: 3.38,
    whip: 1.40,
    kPer9: 7.3,
    bbPer9: 3.1,
    qualityStarts: 10,
  },
  {
    // 平良海馬
    playerId: "lions-6",
    seasonYear: 2025,
    games: 48,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 3,
    losses: 3,
    saves: 20,
    holds: 0,
    blownSaves: 4,
    inningsPitched: 55.0,
    hitsAllowed: 44,
    runsAllowed: 15,
    earnedRuns: 14,
    walksAllowed: 16,
    intentionalWalks: 3,
    hitBatters: 1,
    strikeouts: 58,
    homeRunsAllowed: 3,
    era: 2.29,
    whip: 1.09,
    kPer9: 9.5,
    bbPer9: 2.6,
    qualityStarts: 0,
  },

  // --- Hokkaido Nippon-Ham Fighters ---
  {
    // 伊藤大海
    playerId: "fighters-4",
    seasonYear: 2025,
    games: 26,
    starts: 26,
    completeGames: 2,
    shutouts: 0,
    wins: 9,
    losses: 9,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 152.0,
    hitsAllowed: 148,
    runsAllowed: 56,
    earnedRuns: 52,
    walksAllowed: 48,
    intentionalWalks: 4,
    hitBatters: 5,
    strikeouts: 132,
    homeRunsAllowed: 13,
    era: 3.08,
    whip: 1.29,
    kPer9: 7.8,
    bbPer9: 2.8,
    qualityStarts: 13,
  },
  {
    // 上沢直之
    playerId: "fighters-5",
    seasonYear: 2025,
    games: 24,
    starts: 24,
    completeGames: 1,
    shutouts: 0,
    wins: 8,
    losses: 9,
    saves: 0,
    holds: 0,
    blownSaves: 0,
    inningsPitched: 136.0,
    hitsAllowed: 140,
    runsAllowed: 52,
    earnedRuns: 48,
    walksAllowed: 44,
    intentionalWalks: 4,
    hitBatters: 4,
    strikeouts: 118,
    homeRunsAllowed: 12,
    era: 3.18,
    whip: 1.35,
    kPer9: 7.8,
    bbPer9: 2.9,
    qualityStarts: 11,
  },
  {
    // 田中正義
    playerId: "fighters-6",
    seasonYear: 2025,
    games: 56,
    starts: 0,
    completeGames: 0,
    shutouts: 0,
    wins: 4,
    losses: 3,
    saves: 8,
    holds: 25,
    blownSaves: 3,
    inningsPitched: 64.0,
    hitsAllowed: 50,
    runsAllowed: 18,
    earnedRuns: 16,
    walksAllowed: 20,
    intentionalWalks: 4,
    hitBatters: 2,
    strikeouts: 68,
    homeRunsAllowed: 3,
    era: 2.25,
    whip: 1.09,
    kPer9: 9.6,
    bbPer9: 2.8,
    qualityStarts: 0,
  },

  // ── lions 2026 ──────────────────────
  { playerId: "lions-6", seasonYear: 2026, games:  15, starts:  1, completeGames: 1, shutouts: 0, wins:  7, losses:  2, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 93.00, hitsAllowed:  55, runsAllowed:  15, earnedRuns:  12, walksAllowed: 35, intentionalWalks: 0, hitBatters:  5, strikeouts:  88, homeRunsAllowed:  1, era: 1.16, whip: 0.97, kPer9: 8.52, bbPer9: 3.39, qualityStarts: 0 },

  // ── fighters 2026 ──────────────────────
  { playerId: "fighters-6", seasonYear: 2026, games:   7, starts:  0, completeGames: 0, shutouts: 0, wins:  0, losses:  0, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 14.00, hitsAllowed:  15, runsAllowed:   7, earnedRuns:   4, walksAllowed:  5, intentionalWalks: 0, hitBatters:  0, strikeouts:  13, homeRunsAllowed:  2, era: 2.57, whip: 1.43, kPer9: 8.36, bbPer9: 3.21, qualityStarts: 0 },

  // ── marines 2026 ──────────────────────
  { playerId: "marines-6", seasonYear: 2026, games:   2, starts:  0, completeGames: 0, shutouts: 0, wins:  0, losses:  0, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 7.67, hitsAllowed:   6, runsAllowed:   0, earnedRuns:   0, walksAllowed:  0, intentionalWalks: 0, hitBatters:  0, strikeouts:   7, homeRunsAllowed:  0, era: 0.00, whip: 0.78, kPer9: 8.22, bbPer9: 0.00, qualityStarts: 0 },

  // ── eagles 2026 ──────────────────────
  { playerId: "eagles-6", seasonYear: 2026, games:  15, starts:  0, completeGames: 0, shutouts: 0, wins:  5, losses:  8, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 91.00, hitsAllowed:  88, runsAllowed:  45, earnedRuns:  43, walksAllowed: 26, intentionalWalks: 0, hitBatters:  3, strikeouts: 100, homeRunsAllowed: 14, era: 4.25, whip: 1.25, kPer9: 9.89, bbPer9: 2.57, qualityStarts: 0 },

  // ── hawks 2025 ──────────────────────
  { playerId: "hawks-4", seasonYear: 2025, games:  26, starts:  1, completeGames: 1, shutouts: 0, wins: 14, losses:  9, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 175.00, hitsAllowed: 167, runsAllowed:  67, earnedRuns:  59, walksAllowed: 41, intentionalWalks: 0, hitBatters:  6, strikeouts: 121, homeRunsAllowed: 10, era: 3.03, whip: 1.19, kPer9: 6.22, bbPer9: 2.11, qualityStarts: 0 },

  // ── lions 2025 ──────────────────────
  { playerId: "lions-4", seasonYear: 2025, games:  24, starts:  3, completeGames: 5, shutouts: 3, wins: 10, losses:  5, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 163.67, hitsAllowed: 101, runsAllowed:  38, earnedRuns:  35, walksAllowed: 45, intentionalWalks: 0, hitBatters: 10, strikeouts: 178, homeRunsAllowed:  6, era: 1.92, whip: 0.89, kPer9: 9.79, bbPer9: 2.47, qualityStarts: 0 },
  { playerId: "lions-6", seasonYear: 2025, games:  54, starts:  0, completeGames: 0, shutouts: 0, wins:  4, losses:  2, saves: 31, holds:  8, blownSaves: 0, inningsPitched: 52.67, hitsAllowed:  43, runsAllowed:  12, earnedRuns:  10, walksAllowed: 21, intentionalWalks: 0, hitBatters:  3, strikeouts:  53, homeRunsAllowed:  0, era: 1.71, whip: 1.22, kPer9: 9.06, bbPer9: 3.59, qualityStarts: 0 },

  // ── fighters 2025 ──────────────────────
  { playerId: "fighters-6", seasonYear: 2025, games:  28, starts:  3, completeGames: 4, shutouts: 1, wins:  5, losses:  7, saves:  0, holds:  5, blownSaves: 0, inningsPitched: 95.33, hitsAllowed:  94, runsAllowed:  32, earnedRuns:  31, walksAllowed: 13, intentionalWalks: 0, hitBatters:  2, strikeouts:  62, homeRunsAllowed:  8, era: 2.93, whip: 1.12, kPer9: 5.85, bbPer9: 1.23, qualityStarts: 0 },

  // ── marines 2025 ──────────────────────
  { playerId: "marines-6", seasonYear: 2025, games:  24, starts:  0, completeGames: 2, shutouts: 0, wins:  9, losses:  8, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 160.67, hitsAllowed: 134, runsAllowed:  55, earnedRuns:  47, walksAllowed: 50, intentionalWalks: 0, hitBatters:  6, strikeouts: 161, homeRunsAllowed: 13, era: 2.63, whip: 1.15, kPer9: 9.02, bbPer9: 2.80, qualityStarts: 0 },

  // ── eagles 2025 ──────────────────────
  { playerId: "eagles-6", seasonYear: 2025, games:  13, starts:  0, completeGames: 0, shutouts: 0, wins:  4, losses:  4, saves:  0, holds:  0, blownSaves: 0, inningsPitched: 76.33, hitsAllowed:  65, runsAllowed:  26, earnedRuns:  26, walksAllowed: 25, intentionalWalks: 0, hitBatters:  5, strikeouts:  70, homeRunsAllowed:  4, era: 3.07, whip: 1.18, kPer9: 8.25, bbPer9: 2.95, qualityStarts: 0 },
  { playerId: "eagles-5", seasonYear: 2025, games:  56, starts:  0, completeGames: 0, shutouts: 0, wins:  3, losses:  4, saves: 16, holds: 10, blownSaves: 0, inningsPitched: 56.00, hitsAllowed:  60, runsAllowed:  19, earnedRuns:  19, walksAllowed: 20, intentionalWalks: 0, hitBatters:  2, strikeouts:  43, homeRunsAllowed:  4, era: 3.05, whip: 1.43, kPer9: 6.91, bbPer9: 3.21, qualityStarts: 0 },

  // ── buffaloes 2025 ──────────────────────
  { playerId: "buffaloes-4", seasonYear: 2025, games:   4, starts:  0, completeGames: 0, shutouts: 0, wins:  1, losses:  0, saves:  0, holds:  1, blownSaves: 0, inningsPitched: 21.67, hitsAllowed:  14, runsAllowed:   3, earnedRuns:   3, walksAllowed:  7, intentionalWalks: 0, hitBatters:  1, strikeouts:  31, homeRunsAllowed:  1, era: 1.25, whip: 0.97, kPer9: 12.88, bbPer9: 2.91, qualityStarts: 0 },
];
