export const playersCentral = [
  // Giants (2025年ロスター)
  // 投手
  { id: "giants-1",   teamId: "giants", name: "田中将大",    nameKana: "たなかまさひろ",     jerseyNumber: 11,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1988-11-01", birthPlace: "兵庫",               height: 188, weight: 90,  nationality: "日本",  active: true },
  { id: "giants-2",   teamId: "giants", name: "大勢",        nameKana: "たいせい",           jerseyNumber: 15,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-07-03", birthPlace: "奈良",               height: 186, weight: 90,  nationality: "日本",  active: true },
  { id: "giants-3",   teamId: "giants", name: "西舘勇陽",    nameKana: "にしだてゆうよう",   jerseyNumber: 17,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-07-17", birthPlace: "岩手",               height: 186, weight: 85,  nationality: "日本",  active: true },
  { id: "giants-4",   teamId: "giants", name: "山﨑伊織",    nameKana: "やまさきいおり",     jerseyNumber: 19,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1998-10-31", birthPlace: "愛媛",               height: 181, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-5",   teamId: "giants", name: "戸郷翔征",    nameKana: "とごうしょうせい",   jerseyNumber: 20,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-10-09", birthPlace: "奈良",               height: 183, weight: 87,  nationality: "日本",  active: true },
  { id: "giants-6",   teamId: "giants", name: "今村信貴",    nameKana: "いまむらのぶたか",   jerseyNumber: 26,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "1993-09-04", birthPlace: "熊本",               height: 179, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-7",   teamId: "giants", name: "高橋礼",      nameKana: "たかはしれい",       jerseyNumber: 28,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1995-08-09", birthPlace: "千葉",               height: 186, weight: 95,  nationality: "日本",  active: true },
  { id: "giants-8",   teamId: "giants", name: "グリフィン",  nameKana: "ぐりふぃん",         jerseyNumber: 29,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1995-07-14", birthPlace: "USA",                height: 190, weight: 95,  nationality: "外国",  active: true },
  { id: "giants-9",   teamId: "giants", name: "近藤大亮",    nameKana: "こんどうだいすけ",   jerseyNumber: 30,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1993-09-12", birthPlace: "大阪",               height: 183, weight: 82,  nationality: "日本",  active: true },
  { id: "giants-10",  teamId: "giants", name: "赤星優志",    nameKana: "あかほしゆうじ",     jerseyNumber: 31,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-09-26", birthPlace: "広島",               height: 183, weight: 82,  nationality: "日本",  active: true },
  { id: "giants-11",  teamId: "giants", name: "ケラー",      nameKana: "けらー",             jerseyNumber: 33,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1996-04-28", birthPlace: "USA",                height: 193, weight: 95,  nationality: "外国",  active: true },
  { id: "giants-12",  teamId: "giants", name: "馬場皐輔",    nameKana: "ばばこうすけ",       jerseyNumber: 36,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1993-09-06", birthPlace: "長崎",               height: 190, weight: 90,  nationality: "日本",  active: true },
  { id: "giants-13",  teamId: "giants", name: "中川皓太",    nameKana: "なかがわこうた",     jerseyNumber: 41,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "1996-03-23", birthPlace: "東京",               height: 182, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-14",  teamId: "giants", name: "グズマン",    nameKana: "ぐずまん",           jerseyNumber: 42,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1994-03-14", birthPlace: "Dominican Republic",  height: 190, weight: 90,  nationality: "外国",  active: true },
  { id: "giants-15",  teamId: "giants", name: "田中瑛斗",    nameKana: "たなかえいと",       jerseyNumber: 45,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-12-21", birthPlace: "長崎",               height: 180, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-16",  teamId: "giants", name: "又木鉄平",    nameKana: "またきてっぺい",     jerseyNumber: 46,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "1999-03-24", birthPlace: "兵庫",               height: 178, weight: 74,  nationality: "日本",  active: true },
  { id: "giants-17",  teamId: "giants", name: "森田駿哉",    nameKana: "もりたしゅんや",     jerseyNumber: 47,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "1997-09-10", birthPlace: "岐阜",               height: 178, weight: 75,  nationality: "日本",  active: true },
  { id: "giants-18",  teamId: "giants", name: "田中千晴",    nameKana: "たなかちはる",       jerseyNumber: 48,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2002-05-15", birthPlace: "東京",               height: 180, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-19",  teamId: "giants", name: "バルドナード", nameKana: "ばるどなーど",      jerseyNumber: 49,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1995-01-18", birthPlace: "Venezuela",          height: 188, weight: 88,  nationality: "外国",  active: true },
  { id: "giants-20",  teamId: "giants", name: "高梨雄平",    nameKana: "たかなしゆうへい",   jerseyNumber: 53,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "1994-03-30", birthPlace: "東京",               height: 174, weight: 72,  nationality: "日本",  active: true },
  { id: "giants-21",  teamId: "giants", name: "宮原駿介",    nameKana: "みやはらしゅんすけ", jerseyNumber: 57,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-04-21", birthPlace: "長崎",               height: 185, weight: 83,  nationality: "日本",  active: true },
  { id: "giants-22",  teamId: "giants", name: "船迫大雅",    nameKana: "ふなさこたいが",     jerseyNumber: 58,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2000-03-10", birthPlace: "広島",               height: 185, weight: 83,  nationality: "日本",  active: true },
  { id: "giants-23",  teamId: "giants", name: "横川凱",      nameKana: "よこかわがい",       jerseyNumber: 62,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2001-06-29", birthPlace: "大阪",               height: 183, weight: 83,  nationality: "日本",  active: true },
  { id: "giants-24",  teamId: "giants", name: "泉圭輔",      nameKana: "いずみけいすけ",     jerseyNumber: 63,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1996-04-28", birthPlace: "愛知",               height: 182, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-25",  teamId: "giants", name: "山田龍聖",    nameKana: "やまだりゅうせい",   jerseyNumber: 64,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "2002-08-24", birthPlace: "石川",               height: 186, weight: 87,  nationality: "日本",  active: true },
  { id: "giants-26",  teamId: "giants", name: "石川達也",    nameKana: "いしかわたつや",     jerseyNumber: 65,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "1998-06-20", birthPlace: "愛知",               height: 178, weight: 76,  nationality: "日本",  active: true },
  { id: "giants-27",  teamId: "giants", name: "平内龍太",    nameKana: "ひらうちりゅうた",   jerseyNumber: 66,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-09-11", birthPlace: "高知",               height: 186, weight: 87,  nationality: "日本",  active: true },
  { id: "giants-28",  teamId: "giants", name: "菊地大稀",    nameKana: "きくちだいき",       jerseyNumber: 68,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-06-15", birthPlace: "北海道",             height: 185, weight: 83,  nationality: "日本",  active: true },
  { id: "giants-29",  teamId: "giants", name: "石田充冴",    nameKana: "いしだみつさや",     jerseyNumber: 90,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-04-12", birthPlace: "神奈川",             height: 183, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-30",  teamId: "giants", name: "堀田賢慎",    nameKana: "ほったけんしん",     jerseyNumber: 91,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2002-01-29", birthPlace: "青森",               height: 191, weight: 92,  nationality: "日本",  active: true },
  { id: "giants-31",  teamId: "giants", name: "マルティネス", nameKana: "まるてぃねす",      jerseyNumber: 92,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1993-05-21", birthPlace: "Dominican Republic",  height: 185, weight: 88,  nationality: "外国",  active: true },
  { id: "giants-32",  teamId: "giants", name: "戸田懐生",    nameKana: "とだかいせい",       jerseyNumber: 95,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-08-14", birthPlace: "東京",               height: 178, weight: 75,  nationality: "日本",  active: true },
  { id: "giants-33",  teamId: "giants", name: "井上温大",    nameKana: "いのうえはるた",     jerseyNumber: 97,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2001-12-05", birthPlace: "千葉",               height: 183, weight: 82,  nationality: "日本",  active: true },
  { id: "giants-34",  teamId: "giants", name: "京本眞",      nameKana: "きょうもとまこと",   jerseyNumber: 99,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-07-16", birthPlace: "東京",               height: 186, weight: 88,  nationality: "日本",  active: true },
  // 捕手
  { id: "giants-35",  teamId: "giants", name: "甲斐拓也",    nameKana: "かいたくや",         jerseyNumber: 10,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1992-11-05", birthPlace: "大分",               height: 178, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-36",  teamId: "giants", name: "小林誠司",    nameKana: "こばやしせいじ",     jerseyNumber: 22,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1991-10-17", birthPlace: "広島",               height: 180, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-37",  teamId: "giants", name: "大城卓三",    nameKana: "おおしろたくみ",     jerseyNumber: 24,  position: "捕手" as const,  bats: "左" as const, throws: "右" as const, birthDate: "1993-10-20", birthPlace: "沖縄",               height: 176, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-38",  teamId: "giants", name: "岸田行倫",    nameKana: "きしだゆきみち",     jerseyNumber: 27,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1996-09-13", birthPlace: "大阪",               height: 175, weight: 75,  nationality: "日本",  active: true },
  { id: "giants-39",  teamId: "giants", name: "郡拓也",      nameKana: "こおりたくや",       jerseyNumber: 37,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-06-11", birthPlace: "福岡",               height: 180, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-40",  teamId: "giants", name: "山瀬慎之助",  nameKana: "やませしんのすけ",   jerseyNumber: 67,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-03-14", birthPlace: "石川",               height: 177, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-41",  teamId: "giants", name: "喜多隆介",    nameKana: "きたりゅうすけ",     jerseyNumber: 94,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-01-21", birthPlace: "大阪",               height: 180, weight: 80,  nationality: "日本",  active: true },
  // 内野手
  { id: "giants-42",  teamId: "giants", name: "増田大輝",    nameKana: "ますだだいき",       jerseyNumber: 0,   position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1994-08-18", birthPlace: "愛知",               height: 170, weight: 67,  nationality: "日本",  active: true },
  { id: "giants-43",  teamId: "giants", name: "湯浅大",      nameKana: "ゆあさだい",         jerseyNumber: 0,   position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2003-04-10", birthPlace: "東京",               height: 177, weight: 75,  nationality: "日本",  active: true },
  { id: "giants-44",  teamId: "giants", name: "吉川尚輝",    nameKana: "よしかわなおき",     jerseyNumber: 2,   position: "二塁手" as const, bats: "左" as const, throws: "左" as const, birthDate: "1995-03-09", birthPlace: "岐阜",               height: 178, weight: 75,  nationality: "日本",  active: true },
  { id: "giants-45",  teamId: "giants", name: "門脇誠",      nameKana: "かどわきまこと",     jerseyNumber: 5,   position: "遊撃手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2001-11-14", birthPlace: "石川",               height: 178, weight: 74,  nationality: "日本",  active: true },
  { id: "giants-46",  teamId: "giants", name: "坂本勇人",    nameKana: "さかもとはやと",     jerseyNumber: 6,   position: "遊撃手" as const, bats: "左" as const, throws: "右" as const, birthDate: "1988-12-14", birthPlace: "兵庫",               height: 180, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-47",  teamId: "giants", name: "石塚裕惺",    nameKana: "いしづかひろせい",   jerseyNumber: 23,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2005-11-06", birthPlace: "神奈川",             height: 183, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-48",  teamId: "giants", name: "岡本和真",    nameKana: "おかもとかずま",     jerseyNumber: 25,  position: "一塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1996-06-30", birthPlace: "奈良",               height: 185, weight: 93,  nationality: "日本",  active: true },
  { id: "giants-49",  teamId: "giants", name: "浦田俊輔",    nameKana: "うらたしゅんすけ",   jerseyNumber: 32,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2003-10-05", birthPlace: "福岡",               height: 178, weight: 76,  nationality: "日本",  active: true },
  { id: "giants-50",  teamId: "giants", name: "泉口友汰",    nameKana: "いずみぐちゆうた",   jerseyNumber: 35,  position: "遊撃手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-04-27", birthPlace: "京都",               height: 180, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-51",  teamId: "giants", name: "中山礼都",    nameKana: "なかやまれいと",     jerseyNumber: 40,  position: "遊撃手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-08-09", birthPlace: "愛知",               height: 178, weight: 73,  nationality: "日本",  active: true },
  { id: "giants-52",  teamId: "giants", name: "リチャード",  nameKana: "りちゃーど",         jerseyNumber: 52,  position: "一塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1996-05-10", birthPlace: "Dominican Republic",  height: 188, weight: 95,  nationality: "外国",  active: true },
  { id: "giants-53",  teamId: "giants", name: "荒巻悠",      nameKana: "あらまきゆう",       jerseyNumber: 60,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-01-08", birthPlace: "神奈川",             height: 180, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-54",  teamId: "giants", name: "増田陸",      nameKana: "ますだりく",         jerseyNumber: 61,  position: "三塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2001-02-21", birthPlace: "富山",               height: 180, weight: 80,  nationality: "日本",  active: true },
  // 外野手
  { id: "giants-55",  teamId: "giants", name: "長野久義",    nameKana: "ながのひさよし",     jerseyNumber: 7,   position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1985-09-04", birthPlace: "三重",               height: 181, weight: 88,  nationality: "日本",  active: true },
  { id: "giants-56",  teamId: "giants", name: "丸佳浩",      nameKana: "まるよしひろ",       jerseyNumber: 8,   position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "1989-04-11", birthPlace: "千葉",               height: 178, weight: 90,  nationality: "日本",  active: true },
  { id: "giants-57",  teamId: "giants", name: "萩尾匡也",    nameKana: "はぎおまさや",       jerseyNumber: 12,  position: "外野手" as const, bats: "左" as const, throws: "右" as const, birthDate: "2002-10-19", birthPlace: "大阪",               height: 177, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-58",  teamId: "giants", name: "キャベッジ",  nameKana: "きゃべっじ",         jerseyNumber: 13,  position: "外野手" as const, bats: "左" as const, throws: "右" as const, birthDate: "1998-07-10", birthPlace: "USA",                height: 188, weight: 95,  nationality: "外国",  active: true },
  { id: "giants-59",  teamId: "giants", name: "岡田悠希",    nameKana: "おかだゆうき",       jerseyNumber: 38,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1998-03-15", birthPlace: "愛媛",               height: 178, weight: 77,  nationality: "日本",  active: true },
  { id: "giants-60",  teamId: "giants", name: "フルプ",      nameKana: "ふるぷ",             jerseyNumber: 39,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1995-05-26", birthPlace: "USA",                height: 190, weight: 95,  nationality: "外国",  active: true },
  { id: "giants-61",  teamId: "giants", name: "ヘルナンデス", nameKana: "へるなんです",       jerseyNumber: 42,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1994-03-10", birthPlace: "Venezuela",          height: 185, weight: 88,  nationality: "外国",  active: true },
  { id: "giants-62",  teamId: "giants", name: "重信慎之介",  nameKana: "しげのぶしんのすけ", jerseyNumber: 43,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1993-10-26", birthPlace: "兵庫",               height: 178, weight: 74,  nationality: "日本",  active: true },
  { id: "giants-63",  teamId: "giants", name: "佐々木俊輔",  nameKana: "ささきしゅんすけ",   jerseyNumber: 44,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1999-09-19", birthPlace: "宮城",               height: 182, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-64",  teamId: "giants", name: "オコエ瑠偉",  nameKana: "おこえるい",         jerseyNumber: 50,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1997-05-06", birthPlace: "東京",               height: 186, weight: 84,  nationality: "日本",  active: true },
  { id: "giants-65",  teamId: "giants", name: "浅野翔吾",    nameKana: "あさのしょうご",     jerseyNumber: 51,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-06-07", birthPlace: "香川",               height: 173, weight: 72,  nationality: "日本",  active: true },
  { id: "giants-66",  teamId: "giants", name: "乙坂智",      nameKana: "おとさかさとし",     jerseyNumber: 54,  position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "1994-09-19", birthPlace: "神奈川",             height: 183, weight: 83,  nationality: "日本",  active: true },
  { id: "giants-67",  teamId: "giants", name: "若林楽人",    nameKana: "わかばやしらくと",   jerseyNumber: 59,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1997-10-07", birthPlace: "北海道",             height: 174, weight: 70,  nationality: "日本",  active: true },
  { id: "giants-68",  teamId: "giants", name: "笹原操希",    nameKana: "ささはらもとき",     jerseyNumber: 69,  position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2003-07-12", birthPlace: "富山",               height: 183, weight: 80,  nationality: "日本",  active: true },
  { id: "giants-69",  teamId: "giants", name: "三塚琉生",    nameKana: "みつづかるい",       jerseyNumber: 96,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-04-19", birthPlace: "東京",               height: 180, weight: 78,  nationality: "日本",  active: true },
  { id: "giants-70",  teamId: "giants", name: "鈴木大和",    nameKana: "すずきやまと",       jerseyNumber: 98,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1990-10-04", birthPlace: "神奈川",             height: 172, weight: 68,  nationality: "日本",  active: true },
  // 育成選手
  { id: "giants-71",  teamId: "giants", name: "三浦克也",    nameKana: "みうらかつや",       jerseyNumber: 112, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-05-10", birthPlace: "東京",               height: 182, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-72",  teamId: "giants", name: "堀江正太郎",  nameKana: "ほりえしょうたろう", jerseyNumber: 114, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-03-15", birthPlace: "大阪",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-73",  teamId: "giants", name: "鈴木圭晋",    nameKana: "すずきけいしん",     jerseyNumber: 115, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-07-22", birthPlace: "東京",               height: 180, weight: 77,  nationality: "日本",  active: false },
  { id: "giants-74",  teamId: "giants", name: "千葉隆広",    nameKana: "ちばたかひろ",       jerseyNumber: 116, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-02-08", birthPlace: "千葉",               height: 182, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-75",  teamId: "giants", name: "木下幹也",    nameKana: "きのしたもとや",     jerseyNumber: 118, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-09-20", birthPlace: "大阪",               height: 185, weight: 82,  nationality: "日本",  active: false },
  { id: "giants-76",  teamId: "giants", name: "園田純規",    nameKana: "そのだよしき",       jerseyNumber: 119, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-01-15", birthPlace: "福岡",               height: 182, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-77",  teamId: "giants", name: "松井颯",      nameKana: "まついそう",         jerseyNumber: 121, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-11-10", birthPlace: "愛知",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-78",  teamId: "giants", name: "田村朋輝",    nameKana: "たむらともき",       jerseyNumber: 123, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-05-20", birthPlace: "埼玉",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-79",  teamId: "giants", name: "吉村優聖歩",  nameKana: "よしむらゆうとほ",   jerseyNumber: 126, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-03-01", birthPlace: "大阪",               height: 185, weight: 83,  nationality: "日本",  active: false },
  { id: "giants-80",  teamId: "giants", name: "富田龍",      nameKana: "とみたりゅう",       jerseyNumber: 128, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-08-15", birthPlace: "新潟",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-81",  teamId: "giants", name: "西川歩",      nameKana: "にしかわあゆむ",     jerseyNumber: 129, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-06-22", birthPlace: "兵庫",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-82",  teamId: "giants", name: "吹田志道",    nameKana: "ふきたしどう",       jerseyNumber: 130, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-04-05", birthPlace: "大阪",               height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-83",  teamId: "giants", name: "森本哲星",    nameKana: "もりもとてつせい",   jerseyNumber: 134, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-01-20", birthPlace: "神奈川",             height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-84",  teamId: "giants", name: "ルシアーノ",  nameKana: "るしあーの",         jerseyNumber: 135, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-03-18", birthPlace: "Dominican Republic",  height: 183, weight: 83,  nationality: "外国",  active: false },
  { id: "giants-85",  teamId: "giants", name: "黄錦豪",      nameKana: "ふぁんじんはお",     jerseyNumber: 141, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-11-05", birthPlace: "Taiwan",             height: 182, weight: 80,  nationality: "外国",  active: false },
  { id: "giants-86",  teamId: "giants", name: "鴨打瑛二",    nameKana: "かもうちえいじ",     jerseyNumber: 147, position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2002-08-20", birthPlace: "福岡",               height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-87",  teamId: "giants", name: "直江大輔",    nameKana: "なおえだいすけ",     jerseyNumber: 154, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-04-14", birthPlace: "新潟",               height: 181, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-88",  teamId: "giants", name: "花田侑樹",    nameKana: "はなだゆうき",       jerseyNumber: 163, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-09-10", birthPlace: "京都",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-89",  teamId: "giants", name: "代木大和",    nameKana: "しろきやまと",       jerseyNumber: 168, position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2004-02-14", birthPlace: "東京",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-90",  teamId: "giants", name: "石田隼都",    nameKana: "いしだはやと",       jerseyNumber: 177, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-03-15", birthPlace: "神奈川",             height: 185, weight: 83,  nationality: "日本",  active: false },
  { id: "giants-91",  teamId: "giants", name: "坂本勇人",    nameKana: "さかもとはやと",     jerseyNumber: 106, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2005-06-10", birthPlace: "東京",               height: 177, weight: 73,  nationality: "日本",  active: false },
  { id: "giants-92",  teamId: "giants", name: "大津綾也",    nameKana: "おおつあやや",       jerseyNumber: 110, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-09-08", birthPlace: "大阪",               height: 178, weight: 76,  nationality: "日本",  active: false },
  { id: "giants-93",  teamId: "giants", name: "亀田啓太",    nameKana: "かめだけいた",       jerseyNumber: 122, position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-04-22", birthPlace: "大阪",               height: 178, weight: 76,  nationality: "日本",  active: false },
  { id: "giants-94",  teamId: "giants", name: "坂本達也",    nameKana: "さかもとたつや",     jerseyNumber: 124, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-11-30", birthPlace: "東京",               height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-95",  teamId: "giants", name: "中田歩夢",    nameKana: "なかたあゆむ",       jerseyNumber: 102, position: "外野手" as const, bats: "左" as const, throws: "右" as const, birthDate: "2005-09-15", birthPlace: "大阪",               height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-96",  teamId: "giants", name: "村山源",      nameKana: "むらやまはじめ",     jerseyNumber: 104, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-05-18", birthPlace: "千葉",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-97",  teamId: "giants", name: "田上優弥",    nameKana: "たがみゆうや",       jerseyNumber: 105, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-07-12", birthPlace: "東京",               height: 178, weight: 76,  nationality: "日本",  active: false },
  { id: "giants-98",  teamId: "giants", name: "宇都宮葵星",  nameKana: "うつのみやあおい",   jerseyNumber: 107, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-03-28", birthPlace: "栃木",               height: 180, weight: 78,  nationality: "日本",  active: false },
  { id: "giants-99",  teamId: "giants", name: "相澤白虎",    nameKana: "あいざわびゃっこ",   jerseyNumber: 108, position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2005-01-10", birthPlace: "東京",               height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-100", teamId: "giants", name: "竹下徠空",    nameKana: "たけしたらいく",     jerseyNumber: 125, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-07-20", birthPlace: "神奈川",             height: 183, weight: 80,  nationality: "日本",  active: false },
  { id: "giants-101", teamId: "giants", name: "北村流音",    nameKana: "きたむらりゅうん",   jerseyNumber: 127, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2005-02-15", birthPlace: "大阪",               height: 178, weight: 76,  nationality: "日本",  active: false },
  { id: "giants-102", teamId: "giants", name: "ティマ",      nameKana: "てぃま",             jerseyNumber: 113, position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-06-15", birthPlace: "Dominican Republic",  height: 185, weight: 85,  nationality: "外国",  active: false },
  { id: "giants-103", teamId: "giants", name: "平山功太",    nameKana: "ひらやまこうた",     jerseyNumber: 133, position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-12-05", birthPlace: "神奈川",             height: 177, weight: 77,  nationality: "日本",  active: false },
  { id: "giants-104", teamId: "giants", name: "大城元",      nameKana: "おおしろはじめ",     jerseyNumber: 144, position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-08-28", birthPlace: "沖縄",               height: 175, weight: 75,  nationality: "日本",  active: false },
  { id: "giants-105", teamId: "giants", name: "フェリス",    nameKana: "ふぇりす",           jerseyNumber: 149, position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2001-04-20", birthPlace: "Dominican Republic",  height: 185, weight: 83,  nationality: "外国",  active: false },
  { id: "giants-106", teamId: "giants", name: "舟越秀虎",    nameKana: "ふなこしひでとら",   jerseyNumber: 151, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-10-15", birthPlace: "東京",               height: 180, weight: 78,  nationality: "日本",  active: false },

  // Tigers
  {
    id: "tigers-1",
    teamId: "tigers",
    name: "大山悠輔",
    nameKana: "おおやまゆうすけ",
    jerseyNumber: 3,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-19",
    birthPlace: "鳥取",
    height: 188,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-2",
    teamId: "tigers",
    name: "近本光司",
    nameKana: "ちかもとこうじ",
    jerseyNumber: 5,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-09",
    birthPlace: "兵庫",
    height: 175,
    weight: 75,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-3",
    teamId: "tigers",
    name: "木浪聖也",
    nameKana: "きなみせいや",
    jerseyNumber: 51,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1995-05-26",
    birthPlace: "石川",
    height: 174,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-4",
    teamId: "tigers",
    name: "青柳晃洋",
    nameKana: "あおやぎこうよう",
    jerseyNumber: 21,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-10-21",
    birthPlace: "兵庫",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-5",
    teamId: "tigers",
    name: "西勇輝",
    nameKana: "にしゆうき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-11-10",
    birthPlace: "岡山",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-6",
    teamId: "tigers",
    name: "伊藤将司",
    nameKana: "いとうまさし",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-21",
    birthPlace: "千葉",
    height: 178,
    weight: 82,
    nationality: "日本",
    active: true,
  },

  // BayStars (2025年ロスター)
  {
    id: "baystars-1",
    teamId: "baystars",
    name: "牧秀悟",
    nameKana: "まきしゅうご",
    jerseyNumber: 2,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-04-02",
    birthPlace: "島根",
    height: 182,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-2",
    teamId: "baystars",
    name: "佐野恵太",
    nameKana: "さのけいた",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-28",
    birthPlace: "鳥取",
    height: 174,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-3",
    teamId: "baystars",
    name: "山本祐大",
    nameKana: "やまもとゆうだい",
    jerseyNumber: 50,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-03-25",
    birthPlace: "大阪",
    height: 174,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-4",
    teamId: "baystars",
    name: "東克樹",
    nameKana: "あずまかつき",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-11-18",
    birthPlace: "兵庫",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-5",
    teamId: "baystars",
    name: "宮崎敏郎",
    nameKana: "みやざきとしろう",
    jerseyNumber: 51,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1988-08-14",
    birthPlace: "大分",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-6",
    teamId: "baystars",
    name: "筒香嘉智",
    nameKana: "つつごうよしとも",
    jerseyNumber: 25,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1991-11-26",
    birthPlace: "和歌山",
    height: 185,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-7",
    teamId: "baystars",
    name: "蝦名達夫",
    nameKana: "えびなたつお",
    jerseyNumber: 61,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-05-01",
    birthPlace: "北海道",
    height: 184,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-8",
    teamId: "baystars",
    name: "桑原将志",
    nameKana: "くわはらまさし",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-01-30",
    birthPlace: "広島",
    height: 180,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-9",
    teamId: "baystars",
    name: "神里和毅",
    nameKana: "かみさとかずき",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-04-06",
    birthPlace: "沖縄",
    height: 176,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-10",
    teamId: "baystars",
    name: "入江大生",
    nameKana: "いりえたいせい",
    jerseyNumber: 22,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-07-02",
    birthPlace: "神奈川",
    height: 184,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-11",
    teamId: "baystars",
    name: "伊勢大夢",
    nameKana: "いせひろむ",
    jerseyNumber: 13,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-04-20",
    birthPlace: "熊本",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-12",
    teamId: "baystars",
    name: "アンドレ・ジャクソン",
    nameKana: "あんどれじゃくそん",
    jerseyNumber: 42,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-05-01",
    birthPlace: "California",
    height: 196,
    weight: 104,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-13",
    teamId: "baystars",
    name: "ローワン・ウィック",
    nameKana: "ろーわんうぃっく",
    jerseyNumber: 62,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-11-09",
    birthPlace: "British Columbia",
    height: 196,
    weight: 100,
    nationality: "外国",
    active: true,
  },

  // BayStars (追加選手 第2弾: baystars-22〜36)
  {
    id: "baystars-23",
    teamId: "baystars",
    name: "松尾汐恩",
    nameKana: "まつおしおん",
    jerseyNumber: 5,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-08-05",
    birthPlace: "鳥取",
    height: 176,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-24",
    teamId: "baystars",
    name: "梶原昂希",
    nameKana: "かじわらたかき",
    jerseyNumber: 58,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "2001-09-09",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-26",
    teamId: "baystars",
    name: "知野直人",
    nameKana: "ちのなおと",
    jerseyNumber: 60,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-13",
    birthPlace: "広島",
    height: 175,
    weight: 71,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-27",
    teamId: "baystars",
    name: "柴田竜拓",
    nameKana: "しばたりゅうすけ",
    jerseyNumber: 31,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1993-12-28",
    birthPlace: "神奈川",
    height: 177,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-29",
    teamId: "baystars",
    name: "吉野光樹",
    nameKana: "よしのみつき",
    jerseyNumber: 24,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-05-12",
    birthPlace: "神奈川",
    height: 182,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-30",
    teamId: "baystars",
    name: "深沢鳳介",
    nameKana: "ふかさわほうすけ",
    jerseyNumber: 43,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-04-22",
    birthPlace: "神奈川",
    height: 185,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-31",
    teamId: "baystars",
    name: "坂本裕哉",
    nameKana: "さかもとゆうや",
    jerseyNumber: 20,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-08-12",
    birthPlace: "福岡",
    height: 181,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-32",
    teamId: "baystars",
    name: "森原康平",
    nameKana: "もりはらこうへい",
    jerseyNumber: 45,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-06-14",
    birthPlace: "岡山",
    height: 183,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-33",
    teamId: "baystars",
    name: "砂田毅樹",
    nameKana: "すなだたつき",
    jerseyNumber: 47,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-03-08",
    birthPlace: "神奈川",
    height: 179,
    weight: 78,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-34",
    teamId: "baystars",
    name: "中川颯",
    nameKana: "なかがわそう",
    jerseyNumber: 53,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-04-16",
    birthPlace: "大阪",
    height: 182,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-35",
    teamId: "baystars",
    name: "武藤祐太",
    nameKana: "むとうゆうた",
    jerseyNumber: 28,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-02-20",
    birthPlace: "神奈川",
    height: 178,
    weight: 80,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-36",
    teamId: "baystars",
    name: "三嶋一輝",
    nameKana: "みしまかずき",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-10-29",
    birthPlace: "長崎",
    height: 187,
    weight: 94,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 第3弾: baystars-37〜40)
  {
    id: "baystars-37",
    teamId: "baystars",
    name: "タイラー・オースティン",
    nameKana: "たいらーおーすてぃん",
    jerseyNumber: 3,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-09-06",
    birthPlace: "Georgia",
    height: 188,
    weight: 102,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-38",
    teamId: "baystars",
    name: "山崎康晃",
    nameKana: "やまざきやすあき",
    jerseyNumber: 19,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-10-03",
    birthPlace: "東京",
    height: 178,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-39",
    teamId: "baystars",
    name: "大貫晋一",
    nameKana: "おおぬきしんいち",
    jerseyNumber: 16,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-11-11",
    birthPlace: "長崎",
    height: 182,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-40",
    teamId: "baystars",
    name: "トレバー・バウアー",
    nameKana: "とればーばうあー",
    jerseyNumber: 96,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-01-17",
    birthPlace: "California",
    height: 188,
    weight: 93,
    nationality: "外国",
    active: true,
  },

  // BayStars (追加選手)
  {
    id: "baystars-14",
    teamId: "baystars",
    name: "関根大気",
    nameKana: "せきねたいき",
    jerseyNumber: 63,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-08-15",
    birthPlace: "神奈川",
    height: 179,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-15",
    teamId: "baystars",
    name: "林琢真",
    nameKana: "はやしたくま",
    jerseyNumber: 0,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-04-30",
    birthPlace: "神奈川",
    height: 175,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-16",
    teamId: "baystars",
    name: "京田陽太",
    nameKana: "きょうだようた",
    jerseyNumber: 9,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1994-12-26",
    birthPlace: "滋賀",
    height: 179,
    weight: 77,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-17",
    teamId: "baystars",
    name: "ケイ",
    nameKana: "けい",
    jerseyNumber: 69,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1995-06-09",
    birthPlace: "California",
    height: 193,
    weight: 92,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-18",
    teamId: "baystars",
    name: "石田裕太郎",
    nameKana: "いしだゆうたろう",
    jerseyNumber: 54,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-06-15",
    birthPlace: "広島",
    height: 183,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-19",
    teamId: "baystars",
    name: "平良拳太郎",
    nameKana: "たいらけんたろう",
    jerseyNumber: 59,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-07-01",
    birthPlace: "沖縄",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-20",
    teamId: "baystars",
    name: "上茶谷大河",
    nameKana: "うえちゃたにだいが",
    jerseyNumber: 30,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-09-27",
    birthPlace: "神奈川",
    height: 177,
    weight: 82,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-21",
    teamId: "baystars",
    name: "戸柱恭孝",
    nameKana: "とばしらやすたか",
    jerseyNumber: 10,
    position: "捕手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1990-10-16",
    birthPlace: "島根",
    height: 174,
    weight: 77,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 第4弾: baystars-41〜43)
  {
    id: "baystars-41",
    teamId: "baystars",
    name: "度会隆輝",
    nameKana: "わたらいりゅうき",
    jerseyNumber: 4,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "2002-10-04",
    birthPlace: "千葉",
    height: 183,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-42",
    teamId: "baystars",
    name: "伊藤光",
    nameKana: "いとうひかる",
    jerseyNumber: 29,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-04-19",
    birthPlace: "奈良",
    height: 180,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-43",
    teamId: "baystars",
    name: "三森大貴",
    nameKana: "みつもりだいき",
    jerseyNumber: 26,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-04-06",
    birthPlace: "石川",
    height: 175,
    weight: 74,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 2025年ロスター完全版)
  {
    id: "baystars-44",
    teamId: "baystars",
    name: "森敬斗",
    nameKana: "もりけんと",
    jerseyNumber: 6,
    position: "遊撃手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-11-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-45",
    teamId: "baystars",
    name: "竹田祐",
    nameKana: "たけだゆう",
    jerseyNumber: 12,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-46",
    teamId: "baystars",
    name: "石田健大",
    nameKana: "いしだけんだい",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "左" as const,
    birthDate: "1993-10-08",
    birthPlace: "大阪",
    height: 179,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-47",
    teamId: "baystars",
    name: "徳山壮磨",
    nameKana: "とくやまそうま",
    jerseyNumber: 15,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-28",
    birthPlace: "大阪",
    height: 180,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-48",
    teamId: "baystars",
    name: "小園健太",
    nameKana: "こぞのけんた",
    jerseyNumber: 18,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-09-14",
    birthPlace: "兵庫",
    height: 181,
    weight: 84,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-49",
    teamId: "baystars",
    name: "藤浪晋太郎",
    nameKana: "ふじなみしんたろう",
    jerseyNumber: 27,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-04-12",
    birthPlace: "大阪",
    height: 197,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-50",
    teamId: "baystars",
    name: "勝又温史",
    nameKana: "かつまたあつし",
    jerseyNumber: 28,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-51",
    teamId: "baystars",
    name: "篠木健太郎",
    nameKana: "しのきけんたろう",
    jerseyNumber: 30,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-06-01",
    birthPlace: "千葉",
    height: 183,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-52",
    teamId: "baystars",
    name: "益子京右",
    nameKana: "ましこきょうすけ",
    jerseyNumber: 32,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-53",
    teamId: "baystars",
    name: "武田陸玖",
    nameKana: "たけだりく",
    jerseyNumber: 33,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-54",
    teamId: "baystars",
    name: "松本凌人",
    nameKana: "まつもとりょうと",
    jerseyNumber: 34,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 182,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-55",
    teamId: "baystars",
    name: "橋本達弥",
    nameKana: "はしもとたつや",
    jerseyNumber: 35,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-56",
    teamId: "baystars",
    name: "加藤響",
    nameKana: "かとうひびき",
    jerseyNumber: 37,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-57",
    teamId: "baystars",
    name: "森唯斗",
    nameKana: "もりゆいと",
    jerseyNumber: 38,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-02-10",
    birthPlace: "福岡",
    height: 181,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-58",
    teamId: "baystars",
    name: "若松尚輝",
    nameKana: "わかまつなおき",
    jerseyNumber: 39,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-59",
    teamId: "baystars",
    name: "松本隆之介",
    nameKana: "まつもとりゅうのすけ",
    jerseyNumber: 40,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-06-01",
    birthPlace: "神奈川",
    height: 179,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-60",
    teamId: "baystars",
    name: "佐々木千隼",
    nameKana: "ささきかずはや",
    jerseyNumber: 41,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1995-02-04",
    birthPlace: "神奈川",
    height: 178,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-61",
    teamId: "baystars",
    name: "坂口翔颯",
    nameKana: "さかぐちしょうそう",
    jerseyNumber: 46,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-62",
    teamId: "baystars",
    name: "京山将弥",
    nameKana: "きょうやままさや",
    jerseyNumber: 48,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-05-27",
    birthPlace: "三重",
    height: 182,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-63",
    teamId: "baystars",
    name: "浜地真澄",
    nameKana: "はまちまさすみ",
    jerseyNumber: 52,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-10-05",
    birthPlace: "福岡",
    height: 185,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-64",
    teamId: "baystars",
    name: "井上絢登",
    nameKana: "いのうえあやと",
    jerseyNumber: 55,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-65",
    teamId: "baystars",
    name: "田内真翔",
    nameKana: "たうちまなと",
    jerseyNumber: 56,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-66",
    teamId: "baystars",
    name: "東妻純平",
    nameKana: "ひがしづまじゅんぺい",
    jerseyNumber: 57,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-08-12",
    birthPlace: "神奈川",
    height: 176,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-67",
    teamId: "baystars",
    name: "九鬼隆平",
    nameKana: "くきりゅうへい",
    jerseyNumber: 95,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-09-08",
    birthPlace: "兵庫",
    height: 182,
    weight: 92,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-68",
    teamId: "baystars",
    name: "中川虎大",
    nameKana: "なかがわこた",
    jerseyNumber: 64,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-69",
    teamId: "baystars",
    name: "宮城滝太",
    nameKana: "みやぎたきた",
    jerseyNumber: 65,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-70",
    teamId: "baystars",
    name: "ダヤン・ビシエド",
    nameKana: "だやんびしえど",
    jerseyNumber: 66,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-03-10",
    birthPlace: "Cuba",
    height: 184,
    weight: 100,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-71",
    teamId: "baystars",
    name: "岩田将貴",
    nameKana: "いわたまさき",
    jerseyNumber: 68,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-72",
    teamId: "baystars",
    name: "庄司陽斗",
    nameKana: "しょうじはると",
    jerseyNumber: 91,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-73",
    teamId: "baystars",
    name: "マルセリーノ",
    nameKana: "まるせりーの",
    jerseyNumber: 98,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-01-01",
    birthPlace: "Dominican Republic",
    height: 188,
    weight: 90,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-74",
    teamId: "baystars",
    name: "フォード",
    nameKana: "ふぉーど",
    jerseyNumber: 99,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1998-01-01",
    birthPlace: "USA",
    height: 188,
    weight: 92,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-75",
    teamId: "baystars",
    name: "石上泰輝",
    nameKana: "いしがみたいき",
    jerseyNumber: 44,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-04-21",
    birthPlace: "神奈川",
    height: 175,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  // BayStars 育成選手
  {
    id: "baystars-76",
    teamId: "baystars",
    name: "草野陽斗",
    nameKana: "くさのはると",
    jerseyNumber: 101,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-77",
    teamId: "baystars",
    name: "清水麻成",
    nameKana: "しみずまなり",
    jerseyNumber: 102,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-78",
    teamId: "baystars",
    name: "金渕光希",
    nameKana: "かなぶちみつき",
    jerseyNumber: 103,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-79",
    teamId: "baystars",
    name: "今野瑠斗",
    nameKana: "こんのると",
    jerseyNumber: 108,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-80",
    teamId: "baystars",
    name: "吉岡暖",
    nameKana: "よしおかだん",
    jerseyNumber: 111,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-81",
    teamId: "baystars",
    name: "笠谷俊介",
    nameKana: "かさやしゅんすけ",
    jerseyNumber: 199,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-82",
    teamId: "baystars",
    name: "上甲凌大",
    nameKana: "じょうこうりょうた",
    jerseyNumber: 127,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-83",
    teamId: "baystars",
    name: "近藤大雅",
    nameKana: "こんどうたいが",
    jerseyNumber: 130,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-84",
    teamId: "baystars",
    name: "蓮",
    nameKana: "れん",
    jerseyNumber: 100,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-85",
    teamId: "baystars",
    name: "小笠原蒼",
    nameKana: "おがさわらあおい",
    jerseyNumber: 125,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-86",
    teamId: "baystars",
    name: "西巻賢二",
    nameKana: "にしまきけんじ",
    jerseyNumber: 129,
    position: "内野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1997-07-19",
    birthPlace: "宮城",
    height: 175,
    weight: 75,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-87",
    teamId: "baystars",
    name: "粟飯原龍之介",
    nameKana: "あいばらりゅうのすけ",
    jerseyNumber: 133,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-88",
    teamId: "baystars",
    name: "高見澤郁魅",
    nameKana: "たかみざわふみ",
    jerseyNumber: 193,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },

  // Carp
  {
    id: "carp-1",
    teamId: "carp",
    name: "秋山翔吾",
    nameKana: "あきやましょうご",
    jerseyNumber: 31,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1988-04-16",
    birthPlace: "神奈川",
    height: 182,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-2",
    teamId: "carp",
    name: "西川龍馬",
    nameKana: "にしかわりょうま",
    jerseyNumber: 51,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-07-18",
    birthPlace: "鳥取",
    height: 178,
    weight: 84,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-3",
    teamId: "carp",
    name: "末包昇大",
    nameKana: "すえかねのぶひろ",
    jerseyNumber: 62,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-06-13",
    birthPlace: "広島",
    height: 185,
    weight: 95,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-4",
    teamId: "carp",
    name: "九里亜蓮",
    nameKana: "くりあれん",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-03-07",
    birthPlace: "鳥取",
    height: 181,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-5",
    teamId: "carp",
    name: "床田寛樹",
    nameKana: "とこだひろき",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-07-20",
    birthPlace: "広島",
    height: 182,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-6",
    teamId: "carp",
    name: "大瀬良大地",
    nameKana: "おおせらだいち",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-06-28",
    birthPlace: "長崎",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },

  // Dragons
  {
    id: "dragons-1",
    teamId: "dragons",
    name: "岡林勇希",
    nameKana: "おかばやしゆうき",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "2002-03-06",
    birthPlace: "愛知",
    height: 170,
    weight: 70,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-2",
    teamId: "dragons",
    name: "大島洋平",
    nameKana: "おおしまようへい",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1985-11-04",
    birthPlace: "静岡",
    height: 172,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-3",
    teamId: "dragons",
    name: "石川昂弥",
    nameKana: "いしかわたかや",
    jerseyNumber: 5,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-04",
    birthPlace: "愛知",
    height: 185,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-4",
    teamId: "dragons",
    name: "柳裕也",
    nameKana: "やなぎゆうや",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-22",
    birthPlace: "福岡",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-5",
    teamId: "dragons",
    name: "小笠原慎之介",
    nameKana: "おがさわらしんのすけ",
    jerseyNumber: 20,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-10-11",
    birthPlace: "神奈川",
    height: 183,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-6",
    teamId: "dragons",
    name: "涌井秀章",
    nameKana: "わくいひであき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1986-06-21",
    birthPlace: "埼玉",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },

  // ── 東京ヤクルトスワローズ 2025年ロスター ──────────────────────────────────
  // Swallows
  {
    id: "swallows-1",
    teamId: "swallows",
    name: "村上宗隆",
    nameKana: "むらかみむねたか",
    jerseyNumber: 55,
    position: "三塁手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "2000-02-02",
    birthPlace: "熊本",
    height: 188,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-2",
    teamId: "swallows",
    name: "塩見泰隆",
    nameKana: "しおみやすたか",
    jerseyNumber: 9,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-05-22",
    birthPlace: "鳥取",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-3",
    teamId: "swallows",
    name: "山田哲人",
    nameKana: "やまだてつと",
    jerseyNumber: 1,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-07-16",
    birthPlace: "大阪",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-4",
    teamId: "swallows",
    name: "小川泰弘",
    nameKana: "おがわやすひろ",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-07-26",
    birthPlace: "大阪",
    height: 168,
    weight: 71,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-5",
    teamId: "swallows",
    name: "石川雅規",
    nameKana: "いしかわまさのり",
    jerseyNumber: 19,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1981-01-30",
    birthPlace: "秋田",
    height: 167,
    weight: 68,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-6",
    teamId: "swallows",
    name: "高橋奎二",
    nameKana: "たかはしけいじ",
    jerseyNumber: 47,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-11",
    birthPlace: "沖縄",
    height: 188,
    weight: 83,
    nationality: "日本",
    active: true,
  },

  // 投手（追加）
  { id: "swallows-7",  teamId: "swallows", name: "アビラ",         nameKana: "あびら",             jerseyNumber: 11,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1996-10-15", birthPlace: "Venezuela",         height: 190, weight: 92, nationality: "外国", active: true },
  { id: "swallows-8",  teamId: "swallows", name: "石山泰稚",       nameKana: "いしやまやすとも",   jerseyNumber: 12,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1990-07-17", birthPlace: "兵庫",              height: 192, weight: 90, nationality: "日本", active: true },
  { id: "swallows-9",  teamId: "swallows", name: "中村優斗",       nameKana: "なかむらゆうと",     jerseyNumber: 15,  position: "投手" as const,  bats: "右" as const, throws: "左" as const, birthDate: "1999-04-09", birthPlace: "千葉",              height: 186, weight: 85, nationality: "日本", active: true },
  { id: "swallows-10", teamId: "swallows", name: "清水昇",         nameKana: "しみずのぼる",       jerseyNumber: 17,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1997-11-24", birthPlace: "神奈川",            height: 178, weight: 82, nationality: "日本", active: true },
  { id: "swallows-11", teamId: "swallows", name: "奥川恭伸",       nameKana: "おくがわやすのぶ",   jerseyNumber: 18,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-04-16", birthPlace: "富山",              height: 182, weight: 80, nationality: "日本", active: true },
  { id: "swallows-12", teamId: "swallows", name: "木澤尚文",       nameKana: "きざわなおふみ",     jerseyNumber: 20,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1998-06-10", birthPlace: "東京",              height: 188, weight: 85, nationality: "日本", active: true },
  { id: "swallows-13", teamId: "swallows", name: "吉村貢司郎",     nameKana: "よしむらこうじろう", jerseyNumber: 21,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2001-04-14", birthPlace: "福岡",              height: 186, weight: 85, nationality: "日本", active: true },
  { id: "swallows-14", teamId: "swallows", name: "星知弥",         nameKana: "ほしともや",         jerseyNumber: 24,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1995-09-30", birthPlace: "埼玉",              height: 187, weight: 83, nationality: "日本", active: true },
  { id: "swallows-15", teamId: "swallows", name: "山野太一",       nameKana: "やまのたいち",       jerseyNumber: 26,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2000-09-01", birthPlace: "岡山",              height: 175, weight: 73, nationality: "日本", active: true },
  { id: "swallows-16", teamId: "swallows", name: "松本健吾",       nameKana: "まつもとけんご",     jerseyNumber: 28,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-03-31", birthPlace: "神奈川",            height: 182, weight: 80, nationality: "日本", active: true },
  { id: "swallows-17", teamId: "swallows", name: "荘司宏太",       nameKana: "しょうじこうた",     jerseyNumber: 30,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-05-06", birthPlace: "栃木",              height: 192, weight: 90, nationality: "日本", active: true },
  { id: "swallows-18", teamId: "swallows", name: "田口麗斗",       nameKana: "たぐちれいと",       jerseyNumber: 34,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "1993-04-05", birthPlace: "山口",              height: 180, weight: 82, nationality: "日本", active: true },
  { id: "swallows-19", teamId: "swallows", name: "石原勇輝",       nameKana: "いしはらゆうき",     jerseyNumber: 35,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2003-04-12", birthPlace: "兵庫",              height: 185, weight: 85, nationality: "日本", active: true },
  { id: "swallows-20", teamId: "swallows", name: "ランバート",     nameKana: "らんばーと",         jerseyNumber: 39,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1994-11-18", birthPlace: "California",        height: 195, weight: 98, nationality: "外国", active: true },
  { id: "swallows-21", teamId: "swallows", name: "高梨裕稔",       nameKana: "たかなしひろとし",   jerseyNumber: 40,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1994-02-04", birthPlace: "神奈川",            height: 181, weight: 80, nationality: "日本", active: true },
  { id: "swallows-22", teamId: "swallows", name: "矢崎拓也",       nameKana: "やざきたくや",       jerseyNumber: 41,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1997-04-01", birthPlace: "広島",              height: 186, weight: 88, nationality: "日本", active: true },
  { id: "swallows-23", teamId: "swallows", name: "山本大貴",       nameKana: "やまもとだいき",     jerseyNumber: 43,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1995-02-20", birthPlace: "大阪",              height: 188, weight: 93, nationality: "日本", active: true },
  { id: "swallows-24", teamId: "swallows", name: "大西広樹",       nameKana: "おおにしひろき",     jerseyNumber: 44,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1998-02-13", birthPlace: "大阪",              height: 184, weight: 90, nationality: "日本", active: true },
  { id: "swallows-25", teamId: "swallows", name: "小澤怜史",       nameKana: "おざわさとし",       jerseyNumber: 45,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2000-12-29", birthPlace: "東京",              height: 180, weight: 82, nationality: "日本", active: true },
  { id: "swallows-26", teamId: "swallows", name: "金久保優斗",     nameKana: "かねくぼゆうと",     jerseyNumber: 48,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-11-09", birthPlace: "千葉",              height: 180, weight: 88, nationality: "日本", active: true },
  { id: "swallows-27", teamId: "swallows", name: "山下輝",         nameKana: "やましたひかる",     jerseyNumber: 49,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2001-05-28", birthPlace: "千葉",              height: 193, weight: 95, nationality: "日本", active: true },
  { id: "swallows-28", teamId: "swallows", name: "原樹理",         nameKana: "はらじゅり",         jerseyNumber: 52,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1994-05-16", birthPlace: "兵庫",              height: 182, weight: 90, nationality: "日本", active: true },
  { id: "swallows-29", teamId: "swallows", name: "長谷川宙輝",     nameKana: "はせがわそらき",     jerseyNumber: 53,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "1996-06-14", birthPlace: "兵庫",              height: 183, weight: 84, nationality: "日本", active: true },
  { id: "swallows-30", teamId: "swallows", name: "坂本拓己",       nameKana: "さかもとたくみ",     jerseyNumber: 56,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2001-09-02", birthPlace: "福岡",              height: 180, weight: 80, nationality: "日本", active: true },
  { id: "swallows-31", teamId: "swallows", name: "バウマン",       nameKana: "ばうまん",           jerseyNumber: 58,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1999-03-15", birthPlace: "California",        height: 190, weight: 95, nationality: "外国", active: true },
  { id: "swallows-32", teamId: "swallows", name: "宮川哲",         nameKana: "みやがわさとし",     jerseyNumber: 61,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1998-07-02", birthPlace: "静岡",              height: 182, weight: 82, nationality: "日本", active: true },
  { id: "swallows-33", teamId: "swallows", name: "竹山日向",       nameKana: "たけやまひなた",     jerseyNumber: 62,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-03-14", birthPlace: "宮崎",              height: 185, weight: 80, nationality: "日本", active: true },
  { id: "swallows-34", teamId: "swallows", name: "阪口皓亮",       nameKana: "さかぐちこうすけ",   jerseyNumber: 66,  position: "投手" as const,  bats: "左" as const, throws: "左" as const, birthDate: "2001-12-31", birthPlace: "愛媛",              height: 188, weight: 88, nationality: "日本", active: true },
  { id: "swallows-35", teamId: "swallows", name: "丸山翔大",       nameKana: "まるやましょうた",   jerseyNumber: 68,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-08-13", birthPlace: "神奈川",            height: 175, weight: 72, nationality: "日本", active: true },
  { id: "swallows-36", teamId: "swallows", name: "下川隼佑",       nameKana: "しもかわしゅんすけ", jerseyNumber: 69,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-04-28", birthPlace: "福岡",              height: 183, weight: 80, nationality: "日本", active: true },
  { id: "swallows-37", teamId: "swallows", name: "沼田翔平",       nameKana: "ぬまたしょうへい",   jerseyNumber: 71,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-02-15", birthPlace: "大阪",              height: 178, weight: 78, nationality: "日本", active: true },
  { id: "swallows-38", teamId: "swallows", name: "青柳晃洋",       nameKana: "あおやぎこうよう",   jerseyNumber: 99,  position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1994-10-21", birthPlace: "兵庫",              height: 180, weight: 78, nationality: "日本", active: true },

  // 捕手（追加）
  { id: "swallows-39", teamId: "swallows", name: "古賀優大",       nameKana: "こがゆうだい",       jerseyNumber: 2,   position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1997-12-25", birthPlace: "福岡",              height: 178, weight: 82, nationality: "日本", active: true },
  { id: "swallows-40", teamId: "swallows", name: "中村悠平",       nameKana: "なかむらゆうへい",   jerseyNumber: 27,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1988-03-24", birthPlace: "福岡",              height: 177, weight: 80, nationality: "日本", active: true },
  { id: "swallows-41", teamId: "swallows", name: "松本直樹",       nameKana: "まつもとなおき",     jerseyNumber: 32,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1998-05-24", birthPlace: "兵庫",              height: 173, weight: 73, nationality: "日本", active: true },
  { id: "swallows-42", teamId: "swallows", name: "内山壮真",       nameKana: "うちやまそうま",     jerseyNumber: 33,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-05-23", birthPlace: "愛知",              height: 179, weight: 80, nationality: "日本", active: true },
  { id: "swallows-43", teamId: "swallows", name: "矢野泰二郎",     nameKana: "やのたいじろう",     jerseyNumber: 57,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "1996-03-10", birthPlace: "大阪",              height: 174, weight: 78, nationality: "日本", active: true },
  { id: "swallows-44", teamId: "swallows", name: "鈴木叶",         nameKana: "すずきかなう",       jerseyNumber: 65,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-02-14", birthPlace: "静岡",              height: 180, weight: 78, nationality: "日本", active: true },
  { id: "swallows-45", teamId: "swallows", name: "中川拓真",       nameKana: "なかがわたくま",     jerseyNumber: 90,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-05-01", birthPlace: "東京",              height: 175, weight: 72, nationality: "日本", active: true },
  { id: "swallows-46", teamId: "swallows", name: "橋本星哉",       nameKana: "はしもとせいや",     jerseyNumber: 93,  position: "捕手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-07-11", birthPlace: "神奈川",            height: 178, weight: 80, nationality: "日本", active: true },

  // 内野手（追加）
  { id: "swallows-47", teamId: "swallows", name: "赤羽由紘",       nameKana: "あかばねよしひろ",   jerseyNumber: 0,   position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2003-09-04", birthPlace: "愛知",              height: 175, weight: 70, nationality: "日本", active: false },
  { id: "swallows-48", teamId: "swallows", name: "川端慎吾",       nameKana: "かわばたしんご",     jerseyNumber: 5,   position: "一塁手" as const, bats: "左" as const, throws: "右" as const, birthDate: "1987-01-05", birthPlace: "愛知",              height: 181, weight: 80, nationality: "日本", active: true },
  { id: "swallows-49", teamId: "swallows", name: "長岡秀樹",       nameKana: "ながおかひでき",     jerseyNumber: 7,   position: "遊撃手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2003-01-18", birthPlace: "神奈川",            height: 178, weight: 70, nationality: "日本", active: true },
  { id: "swallows-50", teamId: "swallows", name: "茂木栄五郎",     nameKana: "もぎえいごろう",     jerseyNumber: 8,   position: "遊撃手" as const, bats: "左" as const, throws: "右" as const, birthDate: "1993-07-28", birthPlace: "神奈川",            height: 175, weight: 73, nationality: "日本", active: true },
  { id: "swallows-51", teamId: "swallows", name: "宮本丈",         nameKana: "みやもとじょう",     jerseyNumber: 10,  position: "三塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1995-07-19", birthPlace: "大阪",              height: 179, weight: 76, nationality: "日本", active: true },
  { id: "swallows-52", teamId: "swallows", name: "オスナ",         nameKana: "おすな",             jerseyNumber: 13,  position: "一塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1994-01-15", birthPlace: "Dominican Republic", height: 186, weight: 93, nationality: "外国", active: true },
  { id: "swallows-53", teamId: "swallows", name: "西村瑠伊斗",     nameKana: "にしむらるいと",     jerseyNumber: 36,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-04-10", birthPlace: "東京",              height: 179, weight: 72, nationality: "日本", active: true },
  { id: "swallows-54", teamId: "swallows", name: "山野辺翔",       nameKana: "やまのべしょう",     jerseyNumber: 37,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1996-01-29", birthPlace: "神奈川",            height: 180, weight: 78, nationality: "日本", active: true },
  { id: "swallows-55", teamId: "swallows", name: "北村拓己",       nameKana: "きたむらたくみ",     jerseyNumber: 38,  position: "一塁手" as const, bats: "左" as const, throws: "左" as const, birthDate: "1999-02-07", birthPlace: "大阪",              height: 186, weight: 94, nationality: "日本", active: true },
  { id: "swallows-56", teamId: "swallows", name: "北村恵吾",       nameKana: "きたむらけいご",     jerseyNumber: 50,  position: "三塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2001-05-04", birthPlace: "千葉",              height: 183, weight: 88, nationality: "日本", active: true },
  { id: "swallows-57", teamId: "swallows", name: "田中陽翔",       nameKana: "たなかひなと",       jerseyNumber: 54,  position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-03-12", birthPlace: "東京",              height: 180, weight: 75, nationality: "日本", active: true },
  { id: "swallows-58", teamId: "swallows", name: "武岡龍世",       nameKana: "たけおかりゅうせい", jerseyNumber: 60,  position: "遊撃手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-05-29", birthPlace: "神奈川",            height: 177, weight: 68, nationality: "日本", active: true },
  { id: "swallows-59", teamId: "swallows", name: "伊藤琉偉",       nameKana: "いとうるい",         jerseyNumber: 67,  position: "二塁手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-01-16", birthPlace: "東京",              height: 178, weight: 72, nationality: "日本", active: true },

  // 外野手（追加）
  { id: "swallows-60", teamId: "swallows", name: "並木秀尊",       nameKana: "なみきひでたか",     jerseyNumber: 0,   position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2001-10-03", birthPlace: "千葉",              height: 172, weight: 68, nationality: "日本", active: true },
  { id: "swallows-61", teamId: "swallows", name: "西川遥輝",       nameKana: "にしかわはるき",     jerseyNumber: 3,   position: "外野手" as const, bats: "左" as const, throws: "右" as const, birthDate: "1991-10-09", birthPlace: "兵庫",              height: 183, weight: 82, nationality: "日本", active: true },
  { id: "swallows-62", teamId: "swallows", name: "丸山和郁",       nameKana: "まるやまかずき",     jerseyNumber: 4,   position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2000-11-15", birthPlace: "新潟",              height: 178, weight: 70, nationality: "日本", active: true },
  { id: "swallows-63", teamId: "swallows", name: "サンタナ",       nameKana: "さんたな",           jerseyNumber: 25,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1994-02-24", birthPlace: "Dominican Republic", height: 186, weight: 88, nationality: "外国", active: true },
  { id: "swallows-64", teamId: "swallows", name: "モイセエフ ニキータ", nameKana: "もいせえふにきーた", jerseyNumber: 31, position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2003-08-15", birthPlace: "Russia",            height: 183, weight: 80, nationality: "外国", active: true },
  { id: "swallows-65", teamId: "swallows", name: "澤井廉",         nameKana: "さわいれん",         jerseyNumber: 42,  position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2004-04-25", birthPlace: "福岡",              height: 180, weight: 77, nationality: "日本", active: true },
  { id: "swallows-66", teamId: "swallows", name: "太田賢吾",       nameKana: "おおたけんご",       jerseyNumber: 46,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1998-02-28", birthPlace: "宮城",              height: 175, weight: 70, nationality: "日本", active: true },
  { id: "swallows-67", teamId: "swallows", name: "濱田太貴",       nameKana: "はまだたいき",       jerseyNumber: 51,  position: "外野手" as const, bats: "左" as const, throws: "右" as const, birthDate: "2002-09-18", birthPlace: "大阪",              height: 185, weight: 80, nationality: "日本", active: true },
  { id: "swallows-68", teamId: "swallows", name: "増田珠",         nameKana: "ますだたま",         jerseyNumber: 63,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "1999-04-14", birthPlace: "神奈川",            height: 182, weight: 82, nationality: "日本", active: true },
  { id: "swallows-69", teamId: "swallows", name: "岩田幸宏",       nameKana: "いわたゆきひろ",     jerseyNumber: 64,  position: "外野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2002-07-15", birthPlace: "大阪",              height: 178, weight: 75, nationality: "日本", active: true },

  // 育成選手
  { id: "swallows-70", teamId: "swallows", name: "廣澤優",         nameKana: "ひろさわゆう",       jerseyNumber: 112, position: "外野手" as const, bats: "左" as const, throws: "左" as const, birthDate: "2004-01-20", birthPlace: "大阪",              height: 183, weight: 80, nationality: "日本", active: false },
  { id: "swallows-71", teamId: "swallows", name: "西舘昂汰",       nameKana: "にしだてこうた",     jerseyNumber: 114, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-06-10", birthPlace: "東京",              height: 185, weight: 80, nationality: "日本", active: false },
  { id: "swallows-72", teamId: "swallows", name: "西濱勇星",       nameKana: "にしはまゆうせい",   jerseyNumber: 116, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-09-15", birthPlace: "大阪",              height: 180, weight: 78, nationality: "日本", active: false },
  { id: "swallows-73", teamId: "swallows", name: "翔聖",           nameKana: "しょうせい",         jerseyNumber: 117, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-03-22", birthPlace: "東京",              height: 182, weight: 78, nationality: "日本", active: false },
  { id: "swallows-74", teamId: "swallows", name: "鈴木康平",       nameKana: "すずきこうへい",     jerseyNumber: 118, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2003-08-10", birthPlace: "東京",              height: 183, weight: 80, nationality: "日本", active: false },
  { id: "swallows-75", teamId: "swallows", name: "佐藤琢磨",       nameKana: "さとうたくま",       jerseyNumber: 119, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2004-04-05", birthPlace: "千葉",              height: 180, weight: 75, nationality: "日本", active: false },
  { id: "swallows-76", teamId: "swallows", name: "松本龍之介",     nameKana: "まつもとりゅうのすけ", jerseyNumber: 122, position: "投手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-07-18", birthPlace: "東京",              height: 183, weight: 80, nationality: "日本", active: false },
  { id: "swallows-77", teamId: "swallows", name: "澤野聖悠",       nameKana: "さわのせいゆう",     jerseyNumber: 123, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-10-21", birthPlace: "大阪",              height: 182, weight: 79, nationality: "日本", active: false },
  { id: "swallows-78", teamId: "swallows", name: "根岸辰昇",       nameKana: "ねぎしたつのぼり",   jerseyNumber: 125, position: "内野手" as const, bats: "右" as const, throws: "右" as const, birthDate: "2004-06-30", birthPlace: "東京",              height: 180, weight: 75, nationality: "日本", active: false },
  { id: "swallows-79", teamId: "swallows", name: "髙野颯太",       nameKana: "たかのそうた",       jerseyNumber: 126, position: "投手" as const,  bats: "右" as const, throws: "右" as const, birthDate: "2005-02-12", birthPlace: "神奈川",            height: 185, weight: 82, nationality: "日本", active: false },
];
