export const playersPacific: {
  id: string;
  teamId: string;
  name: string;
  nameKana: string;
  jerseyNumber: number;
  position: "投手" | "捕手" | "一塁手" | "二塁手" | "三塁手" | "遊撃手" | "外野手";
  bats: "右" | "左" | "両";
  throws: "右" | "左" | "両";
  birthDate: string;
  birthPlace: string;
  height: number;
  weight: number;
  nationality: string;
  active: true;
}[] = [
  // ── 福岡ソフトバンクホークス ──────────────────────────────────────────────
  {
    id: "hawks-1",
    teamId: "hawks",
    name: "近藤健介",
    nameKana: "こんどうけんすけ",
    jerseyNumber: 5,
    position: "外野手",
    bats: "左",
    throws: "左",
    birthDate: "1993-08-18",
    birthPlace: "神奈川",
    height: 180,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "hawks-2",
    teamId: "hawks",
    name: "柳田悠岐",
    nameKana: "やなぎたゆうき",
    jerseyNumber: 9,
    position: "外野手",
    bats: "左",
    throws: "右",
    birthDate: "1988-10-09",
    birthPlace: "広島",
    height: 188,
    weight: 95,
    nationality: "日本",
    active: true,
  },
  {
    id: "hawks-3",
    teamId: "hawks",
    name: "甲斐拓也",
    nameKana: "かいたくや",
    jerseyNumber: 19,
    position: "捕手",
    bats: "右",
    throws: "右",
    birthDate: "1992-11-05",
    birthPlace: "大分",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "hawks-4",
    teamId: "hawks",
    name: "有原航平",
    nameKana: "ありはらこうへい",
    jerseyNumber: 21,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1991-09-27",
    birthPlace: "広島",
    height: 183,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "hawks-5",
    teamId: "hawks",
    name: "石川柊太",
    nameKana: "いしかわしゅうた",
    jerseyNumber: 17,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1993-01-19",
    birthPlace: "三重",
    height: 184,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "hawks-6",
    teamId: "hawks",
    name: "モイネロ",
    nameKana: "もいねろ",
    jerseyNumber: 16,
    position: "投手",
    bats: "左",
    throws: "左",
    birthDate: "1995-10-25",
    birthPlace: "Cuba",
    height: 185,
    weight: 82,
    nationality: "外国",
    active: true,
  },

  // ── 千葉ロッテマリーンズ ──────────────────────────────────────────────────
  {
    id: "marines-1",
    teamId: "marines",
    name: "角中勝也",
    nameKana: "かどなかかつや",
    jerseyNumber: 31,
    position: "外野手",
    bats: "左",
    throws: "左",
    birthDate: "1986-08-25",
    birthPlace: "沖縄",
    height: 174,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "marines-2",
    teamId: "marines",
    name: "中村奨吾",
    nameKana: "なかむらしょうご",
    jerseyNumber: 3,
    position: "二塁手",
    bats: "右",
    throws: "右",
    birthDate: "1993-06-17",
    birthPlace: "奈良",
    height: 178,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "marines-3",
    teamId: "marines",
    name: "安田尚憲",
    nameKana: "やすだなおのり",
    jerseyNumber: 34,
    position: "一塁手",
    bats: "左",
    throws: "左",
    birthDate: "1999-04-15",
    birthPlace: "大阪",
    height: 183,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "marines-4",
    teamId: "marines",
    name: "佐々木朗希",
    nameKana: "ささきろうき",
    jerseyNumber: 11,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "2001-11-03",
    birthPlace: "岩手",
    height: 190,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "marines-5",
    teamId: "marines",
    name: "小島和哉",
    nameKana: "おじまかずや",
    jerseyNumber: 14,
    position: "投手",
    bats: "左",
    throws: "左",
    birthDate: "1996-12-27",
    birthPlace: "埼玉",
    height: 178,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "marines-6",
    teamId: "marines",
    name: "種市篤暉",
    nameKana: "たねいちあつき",
    jerseyNumber: 18,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1998-02-13",
    birthPlace: "青森",
    height: 190,
    weight: 88,
    nationality: "日本",
    active: true,
  },

  // ── 東北楽天ゴールデンイーグルス ──────────────────────────────────────────
  {
    id: "eagles-1",
    teamId: "eagles",
    name: "浅村栄斗",
    nameKana: "あさむらえいと",
    jerseyNumber: 3,
    position: "二塁手",
    bats: "右",
    throws: "右",
    birthDate: "1990-11-14",
    birthPlace: "大阪",
    height: 180,
    weight: 92,
    nationality: "日本",
    active: true,
  },
  {
    id: "eagles-2",
    teamId: "eagles",
    name: "辰己涼介",
    nameKana: "たつみりょうすけ",
    jerseyNumber: 1,
    position: "外野手",
    bats: "左",
    throws: "左",
    birthDate: "1997-01-27",
    birthPlace: "兵庫",
    height: 180,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "eagles-3",
    teamId: "eagles",
    name: "島内宏明",
    nameKana: "しまうちひろあき",
    jerseyNumber: 9,
    position: "外野手",
    bats: "右",
    throws: "右",
    birthDate: "1990-04-01",
    birthPlace: "福岡",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "eagles-4",
    teamId: "eagles",
    name: "田中将大",
    nameKana: "たなかまさひろ",
    jerseyNumber: 18,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1988-11-01",
    birthPlace: "兵庫",
    height: 188,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "eagles-5",
    teamId: "eagles",
    name: "則本昂大",
    nameKana: "のりもとたかひろ",
    jerseyNumber: 13,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1991-08-24",
    birthPlace: "三重",
    height: 178,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "eagles-6",
    teamId: "eagles",
    name: "荘司康誠",
    nameKana: "しょうじこうせい",
    jerseyNumber: 11,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "2001-03-19",
    birthPlace: "新潟",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },

  // ── オリックス・バファローズ ───────────────────────────────────────────────
  {
    id: "buffaloes-1",
    teamId: "buffaloes",
    name: "頓宮裕真",
    nameKana: "とんぐうゆうま",
    jerseyNumber: 26,
    position: "捕手",
    bats: "右",
    throws: "右",
    birthDate: "1997-01-17",
    birthPlace: "岡山",
    height: 181,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "buffaloes-2",
    teamId: "buffaloes",
    name: "中川圭太",
    nameKana: "なかがわけいた",
    jerseyNumber: 5,
    position: "外野手",
    bats: "左",
    throws: "左",
    birthDate: "1996-02-16",
    birthPlace: "大阪",
    height: 176,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "buffaloes-3",
    teamId: "buffaloes",
    name: "西野真弘",
    nameKana: "にしのまさひろ",
    jerseyNumber: 4,
    position: "二塁手",
    bats: "右",
    throws: "右",
    birthDate: "1991-09-28",
    birthPlace: "大阪",
    height: 172,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "buffaloes-4",
    teamId: "buffaloes",
    name: "山下舜平大",
    nameKana: "やましたしゅんぺいた",
    jerseyNumber: 11,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "2002-07-04",
    birthPlace: "福岡",
    height: 191,
    weight: 93,
    nationality: "日本",
    active: true,
  },
  {
    id: "buffaloes-5",
    teamId: "buffaloes",
    name: "宮城大弥",
    nameKana: "みやぎひろや",
    jerseyNumber: 13,
    position: "投手",
    bats: "左",
    throws: "左",
    birthDate: "2002-01-09",
    birthPlace: "沖縄",
    height: 177,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "buffaloes-6",
    teamId: "buffaloes",
    name: "田嶋大樹",
    nameKana: "たじまだいき",
    jerseyNumber: 14,
    position: "投手",
    bats: "左",
    throws: "左",
    birthDate: "1997-03-11",
    birthPlace: "茨城",
    height: 180,
    weight: 82,
    nationality: "日本",
    active: true,
  },

  // ── 埼玉西武ライオンズ ────────────────────────────────────────────────────
  {
    id: "lions-1",
    teamId: "lions",
    name: "源田壮亮",
    nameKana: "げんだそうすけ",
    jerseyNumber: 2,
    position: "遊撃手",
    bats: "左",
    throws: "右",
    birthDate: "1993-05-16",
    birthPlace: "大分",
    height: 175,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "lions-2",
    teamId: "lions",
    name: "外崎修汰",
    nameKana: "とのさきしゅうた",
    jerseyNumber: 3,
    position: "二塁手",
    bats: "右",
    throws: "右",
    birthDate: "1993-04-18",
    birthPlace: "鳥取",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "lions-3",
    teamId: "lions",
    name: "中村剛也",
    nameKana: "なかむらたけや",
    jerseyNumber: 25,
    position: "一塁手",
    bats: "右",
    throws: "右",
    birthDate: "1983-06-26",
    birthPlace: "大阪",
    height: 175,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "lions-4",
    teamId: "lions",
    name: "今井達也",
    nameKana: "いまいたつや",
    jerseyNumber: 11,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1997-07-01",
    birthPlace: "栃木",
    height: 185,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "lions-5",
    teamId: "lions",
    name: "高橋光成",
    nameKana: "たかはしこうせい",
    jerseyNumber: 16,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1997-07-31",
    birthPlace: "群馬",
    height: 192,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "lions-6",
    teamId: "lions",
    name: "平良海馬",
    nameKana: "たいらかいま",
    jerseyNumber: 13,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "2001-01-13",
    birthPlace: "沖縄",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },

  // ── 北海道日本ハムファイターズ ────────────────────────────────────────────
  {
    id: "fighters-1",
    teamId: "fighters",
    name: "万波中正",
    nameKana: "よろずなみかまさ",
    jerseyNumber: 32,
    position: "外野手",
    bats: "右",
    throws: "右",
    birthDate: "2000-10-25",
    birthPlace: "神奈川",
    height: 193,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "fighters-2",
    teamId: "fighters",
    name: "松本剛",
    nameKana: "まつもとごう",
    jerseyNumber: 5,
    position: "外野手",
    bats: "右",
    throws: "右",
    birthDate: "1994-10-07",
    birthPlace: "神奈川",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "fighters-3",
    teamId: "fighters",
    name: "田宮裕涼",
    nameKana: "たみやゆうすけ",
    jerseyNumber: 27,
    position: "捕手",
    bats: "左",
    throws: "右",
    birthDate: "2001-05-04",
    birthPlace: "千葉",
    height: 175,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "fighters-4",
    teamId: "fighters",
    name: "上沢直之",
    nameKana: "うわさわなおゆき",
    jerseyNumber: 11,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1993-10-23",
    birthPlace: "千葉",
    height: 186,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "fighters-5",
    teamId: "fighters",
    name: "伊藤大海",
    nameKana: "いとうひろみ",
    jerseyNumber: 14,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "1998-07-06",
    birthPlace: "北海道",
    height: 177,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "fighters-6",
    teamId: "fighters",
    name: "金村尚真",
    nameKana: "かねむらなおまさ",
    jerseyNumber: 28,
    position: "投手",
    bats: "右",
    throws: "右",
    birthDate: "2001-12-08",
    birthPlace: "広島",
    height: 176,
    weight: 76,
    nationality: "日本",
    active: true,
  },
];
