export const playersCentral = [
  // Giants
  {
    id: "giants-1",
    teamId: "giants",
    name: "岡本和真",
    nameKana: "おかもとかずま",
    jerseyNumber: 25,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-06-30",
    birthPlace: "奈良",
    height: 185,
    weight: 93,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-2",
    teamId: "giants",
    name: "坂本勇人",
    nameKana: "さかもとはやと",
    jerseyNumber: 6,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1988-12-14",
    birthPlace: "兵庫",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-3",
    teamId: "giants",
    name: "丸佳浩",
    nameKana: "まるよしひろ",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1989-04-11",
    birthPlace: "千葉",
    height: 178,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-4",
    teamId: "giants",
    name: "戸郷翔征",
    nameKana: "とごうしょうせい",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-10-09",
    birthPlace: "奈良",
    height: 183,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-5",
    teamId: "giants",
    name: "菅野智之",
    nameKana: "すがのともゆき",
    jerseyNumber: 18,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-10-11",
    birthPlace: "東京",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-6",
    teamId: "giants",
    name: "高橋礼",
    nameKana: "たかはしれい",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "右" as const,
    throws: "両" as const,
    birthDate: "1995-08-09",
    birthPlace: "千葉",
    height: 186,
    weight: 95,
    nationality: "日本",
    active: true,
  },

  // Tigers
  {
    id: "tigers-1",
    teamId: "tigers",
    name: "大山悠輔",
    nameKana: "おおやまゆうすけ",
    jerseyNumber: 3,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-19",
    birthPlace: "鳥取",
    height: 188,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-2",
    teamId: "tigers",
    name: "近本光司",
    nameKana: "ちかもとこうじ",
    jerseyNumber: 5,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-09",
    birthPlace: "兵庫",
    height: 175,
    weight: 75,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-3",
    teamId: "tigers",
    name: "木浪聖也",
    nameKana: "きなみせいや",
    jerseyNumber: 51,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1995-05-26",
    birthPlace: "石川",
    height: 174,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-4",
    teamId: "tigers",
    name: "青柳晃洋",
    nameKana: "あおやぎこうよう",
    jerseyNumber: 21,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-10-21",
    birthPlace: "兵庫",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-5",
    teamId: "tigers",
    name: "西勇輝",
    nameKana: "にしゆうき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-11-10",
    birthPlace: "岡山",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-6",
    teamId: "tigers",
    name: "伊藤将司",
    nameKana: "いとうまさし",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-21",
    birthPlace: "千葉",
    height: 178,
    weight: 82,
    nationality: "日本",
    active: true,
  },

  // BayStars (2025年ロスター)
  {
    id: "baystars-1",
    teamId: "baystars",
    name: "牧秀悟",
    nameKana: "まきしゅうご",
    jerseyNumber: 2,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-04-02",
    birthPlace: "島根",
    height: 182,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-2",
    teamId: "baystars",
    name: "佐野恵太",
    nameKana: "さのけいた",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-28",
    birthPlace: "鳥取",
    height: 174,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-3",
    teamId: "baystars",
    name: "山本祐大",
    nameKana: "やまもとゆうだい",
    jerseyNumber: 50,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-03-25",
    birthPlace: "大阪",
    height: 174,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-4",
    teamId: "baystars",
    name: "東克樹",
    nameKana: "あずまかつき",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-11-18",
    birthPlace: "兵庫",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-5",
    teamId: "baystars",
    name: "宮崎敏郎",
    nameKana: "みやざきとしろう",
    jerseyNumber: 51,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1988-08-14",
    birthPlace: "大分",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-6",
    teamId: "baystars",
    name: "筒香嘉智",
    nameKana: "つつごうよしとも",
    jerseyNumber: 25,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1991-11-26",
    birthPlace: "和歌山",
    height: 185,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-7",
    teamId: "baystars",
    name: "蝦名達夫",
    nameKana: "えびなたつお",
    jerseyNumber: 61,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-05-01",
    birthPlace: "北海道",
    height: 184,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-8",
    teamId: "baystars",
    name: "桑原将志",
    nameKana: "くわはらまさし",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-01-30",
    birthPlace: "広島",
    height: 180,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-9",
    teamId: "baystars",
    name: "神里和毅",
    nameKana: "かみさとかずき",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-04-06",
    birthPlace: "沖縄",
    height: 176,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-10",
    teamId: "baystars",
    name: "入江大生",
    nameKana: "いりえたいせい",
    jerseyNumber: 22,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-07-02",
    birthPlace: "神奈川",
    height: 184,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-11",
    teamId: "baystars",
    name: "伊勢大夢",
    nameKana: "いせひろむ",
    jerseyNumber: 13,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-04-20",
    birthPlace: "熊本",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-12",
    teamId: "baystars",
    name: "アンドレ・ジャクソン",
    nameKana: "あんどれじゃくそん",
    jerseyNumber: 42,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-05-01",
    birthPlace: "California",
    height: 196,
    weight: 104,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-13",
    teamId: "baystars",
    name: "ローワン・ウィック",
    nameKana: "ろーわんうぃっく",
    jerseyNumber: 62,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-11-09",
    birthPlace: "British Columbia",
    height: 196,
    weight: 100,
    nationality: "外国",
    active: true,
  },

  // BayStars (追加選手 第2弾: baystars-22〜36)
  {
    id: "baystars-23",
    teamId: "baystars",
    name: "松尾汐恩",
    nameKana: "まつおしおん",
    jerseyNumber: 5,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-08-05",
    birthPlace: "鳥取",
    height: 176,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-24",
    teamId: "baystars",
    name: "梶原昂希",
    nameKana: "かじわらたかき",
    jerseyNumber: 58,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "2001-09-09",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-26",
    teamId: "baystars",
    name: "知野直人",
    nameKana: "ちのなおと",
    jerseyNumber: 60,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-13",
    birthPlace: "広島",
    height: 175,
    weight: 71,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-27",
    teamId: "baystars",
    name: "柴田竜拓",
    nameKana: "しばたりゅうすけ",
    jerseyNumber: 31,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1993-12-28",
    birthPlace: "神奈川",
    height: 177,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-29",
    teamId: "baystars",
    name: "吉野光樹",
    nameKana: "よしのみつき",
    jerseyNumber: 24,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-05-12",
    birthPlace: "神奈川",
    height: 182,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-30",
    teamId: "baystars",
    name: "深沢鳳介",
    nameKana: "ふかさわほうすけ",
    jerseyNumber: 43,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-04-22",
    birthPlace: "神奈川",
    height: 185,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-31",
    teamId: "baystars",
    name: "坂本裕哉",
    nameKana: "さかもとゆうや",
    jerseyNumber: 20,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-08-12",
    birthPlace: "福岡",
    height: 181,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-32",
    teamId: "baystars",
    name: "森原康平",
    nameKana: "もりはらこうへい",
    jerseyNumber: 45,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-06-14",
    birthPlace: "岡山",
    height: 183,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-33",
    teamId: "baystars",
    name: "砂田毅樹",
    nameKana: "すなだたつき",
    jerseyNumber: 47,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-03-08",
    birthPlace: "神奈川",
    height: 179,
    weight: 78,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-34",
    teamId: "baystars",
    name: "中川颯",
    nameKana: "なかがわそう",
    jerseyNumber: 53,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-04-16",
    birthPlace: "大阪",
    height: 182,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-35",
    teamId: "baystars",
    name: "武藤祐太",
    nameKana: "むとうゆうた",
    jerseyNumber: 28,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-02-20",
    birthPlace: "神奈川",
    height: 178,
    weight: 80,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-36",
    teamId: "baystars",
    name: "三嶋一輝",
    nameKana: "みしまかずき",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-10-29",
    birthPlace: "長崎",
    height: 187,
    weight: 94,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 第3弾: baystars-37〜40)
  {
    id: "baystars-37",
    teamId: "baystars",
    name: "タイラー・オースティン",
    nameKana: "たいらーおーすてぃん",
    jerseyNumber: 3,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-09-06",
    birthPlace: "Georgia",
    height: 188,
    weight: 102,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-38",
    teamId: "baystars",
    name: "山崎康晃",
    nameKana: "やまざきやすあき",
    jerseyNumber: 19,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-10-03",
    birthPlace: "東京",
    height: 178,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-39",
    teamId: "baystars",
    name: "大貫晋一",
    nameKana: "おおぬきしんいち",
    jerseyNumber: 16,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-11-11",
    birthPlace: "長崎",
    height: 182,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-40",
    teamId: "baystars",
    name: "トレバー・バウアー",
    nameKana: "とればーばうあー",
    jerseyNumber: 96,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-01-17",
    birthPlace: "California",
    height: 188,
    weight: 93,
    nationality: "外国",
    active: true,
  },

  // BayStars (追加選手)
  {
    id: "baystars-14",
    teamId: "baystars",
    name: "関根大気",
    nameKana: "せきねたいき",
    jerseyNumber: 63,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-08-15",
    birthPlace: "神奈川",
    height: 179,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-15",
    teamId: "baystars",
    name: "林琢真",
    nameKana: "はやしたくま",
    jerseyNumber: 0,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-04-30",
    birthPlace: "神奈川",
    height: 175,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-16",
    teamId: "baystars",
    name: "京田陽太",
    nameKana: "きょうだようた",
    jerseyNumber: 9,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1994-12-26",
    birthPlace: "滋賀",
    height: 179,
    weight: 77,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-17",
    teamId: "baystars",
    name: "ケイ",
    nameKana: "けい",
    jerseyNumber: 69,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1995-06-09",
    birthPlace: "California",
    height: 193,
    weight: 92,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-18",
    teamId: "baystars",
    name: "石田裕太郎",
    nameKana: "いしだゆうたろう",
    jerseyNumber: 54,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-06-15",
    birthPlace: "広島",
    height: 183,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-19",
    teamId: "baystars",
    name: "平良拳太郎",
    nameKana: "たいらけんたろう",
    jerseyNumber: 59,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-07-01",
    birthPlace: "沖縄",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-20",
    teamId: "baystars",
    name: "上茶谷大河",
    nameKana: "うえちゃたにだいが",
    jerseyNumber: 30,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-09-27",
    birthPlace: "神奈川",
    height: 177,
    weight: 82,
    nationality: "日本",
    active: false,
  },
  {
    id: "baystars-21",
    teamId: "baystars",
    name: "戸柱恭孝",
    nameKana: "とばしらやすたか",
    jerseyNumber: 10,
    position: "捕手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1990-10-16",
    birthPlace: "島根",
    height: 174,
    weight: 77,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 第4弾: baystars-41〜43)
  {
    id: "baystars-41",
    teamId: "baystars",
    name: "度会隆輝",
    nameKana: "わたらいりゅうき",
    jerseyNumber: 4,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "2002-10-04",
    birthPlace: "千葉",
    height: 183,
    weight: 83,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-42",
    teamId: "baystars",
    name: "伊藤光",
    nameKana: "いとうひかる",
    jerseyNumber: 29,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-04-19",
    birthPlace: "奈良",
    height: 180,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-43",
    teamId: "baystars",
    name: "三森大貴",
    nameKana: "みつもりだいき",
    jerseyNumber: 26,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-04-06",
    birthPlace: "石川",
    height: 175,
    weight: 74,
    nationality: "日本",
    active: true,
  },

  // BayStars (追加選手 2025年ロスター完全版)
  {
    id: "baystars-44",
    teamId: "baystars",
    name: "森敬斗",
    nameKana: "もりけんと",
    jerseyNumber: 6,
    position: "遊撃手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-11-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-45",
    teamId: "baystars",
    name: "竹田祐",
    nameKana: "たけだゆう",
    jerseyNumber: 12,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-46",
    teamId: "baystars",
    name: "石田健大",
    nameKana: "いしだけんだい",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "左" as const,
    birthDate: "1993-10-08",
    birthPlace: "大阪",
    height: 179,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-47",
    teamId: "baystars",
    name: "徳山壮磨",
    nameKana: "とくやまそうま",
    jerseyNumber: 15,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-28",
    birthPlace: "大阪",
    height: 180,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-48",
    teamId: "baystars",
    name: "小園健太",
    nameKana: "こぞのけんた",
    jerseyNumber: 18,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-09-14",
    birthPlace: "兵庫",
    height: 181,
    weight: 84,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-49",
    teamId: "baystars",
    name: "藤浪晋太郎",
    nameKana: "ふじなみしんたろう",
    jerseyNumber: 27,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-04-12",
    birthPlace: "大阪",
    height: 197,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-50",
    teamId: "baystars",
    name: "勝又温史",
    nameKana: "かつまたあつし",
    jerseyNumber: 28,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-51",
    teamId: "baystars",
    name: "篠木健太郎",
    nameKana: "しのきけんたろう",
    jerseyNumber: 30,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-06-01",
    birthPlace: "千葉",
    height: 183,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-52",
    teamId: "baystars",
    name: "益子京右",
    nameKana: "ましこきょうすけ",
    jerseyNumber: 32,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-53",
    teamId: "baystars",
    name: "武田陸玖",
    nameKana: "たけだりく",
    jerseyNumber: 33,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-54",
    teamId: "baystars",
    name: "松本凌人",
    nameKana: "まつもとりょうと",
    jerseyNumber: 34,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 182,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-55",
    teamId: "baystars",
    name: "橋本達弥",
    nameKana: "はしもとたつや",
    jerseyNumber: 35,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-56",
    teamId: "baystars",
    name: "加藤響",
    nameKana: "かとうひびき",
    jerseyNumber: 37,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-57",
    teamId: "baystars",
    name: "森唯斗",
    nameKana: "もりゆいと",
    jerseyNumber: 38,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1993-02-10",
    birthPlace: "福岡",
    height: 181,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-58",
    teamId: "baystars",
    name: "若松尚輝",
    nameKana: "わかまつなおき",
    jerseyNumber: 39,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-59",
    teamId: "baystars",
    name: "松本隆之介",
    nameKana: "まつもとりゅうのすけ",
    jerseyNumber: 40,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-06-01",
    birthPlace: "神奈川",
    height: 179,
    weight: 79,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-60",
    teamId: "baystars",
    name: "佐々木千隼",
    nameKana: "ささきかずはや",
    jerseyNumber: 41,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1995-02-04",
    birthPlace: "神奈川",
    height: 178,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-61",
    teamId: "baystars",
    name: "坂口翔颯",
    nameKana: "さかぐちしょうそう",
    jerseyNumber: 46,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-62",
    teamId: "baystars",
    name: "京山将弥",
    nameKana: "きょうやままさや",
    jerseyNumber: 48,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-05-27",
    birthPlace: "三重",
    height: 182,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-63",
    teamId: "baystars",
    name: "浜地真澄",
    nameKana: "はまちまさすみ",
    jerseyNumber: 52,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-10-05",
    birthPlace: "福岡",
    height: 185,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-64",
    teamId: "baystars",
    name: "井上絢登",
    nameKana: "いのうえあやと",
    jerseyNumber: 55,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-65",
    teamId: "baystars",
    name: "田内真翔",
    nameKana: "たうちまなと",
    jerseyNumber: 56,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 76,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-66",
    teamId: "baystars",
    name: "東妻純平",
    nameKana: "ひがしづまじゅんぺい",
    jerseyNumber: 57,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-08-12",
    birthPlace: "神奈川",
    height: 176,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-67",
    teamId: "baystars",
    name: "九鬼隆平",
    nameKana: "くきりゅうへい",
    jerseyNumber: 95,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-09-08",
    birthPlace: "兵庫",
    height: 182,
    weight: 92,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-68",
    teamId: "baystars",
    name: "中川虎大",
    nameKana: "なかがわこた",
    jerseyNumber: 64,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 181,
    weight: 82,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-69",
    teamId: "baystars",
    name: "宮城滝太",
    nameKana: "みやぎたきた",
    jerseyNumber: 65,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2003-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-70",
    teamId: "baystars",
    name: "ダヤン・ビシエド",
    nameKana: "だやんびしえど",
    jerseyNumber: 66,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-03-10",
    birthPlace: "Cuba",
    height: 184,
    weight: 100,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-71",
    teamId: "baystars",
    name: "岩田将貴",
    nameKana: "いわたまさき",
    jerseyNumber: 68,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-72",
    teamId: "baystars",
    name: "庄司陽斗",
    nameKana: "しょうじはると",
    jerseyNumber: 91,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2001-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-73",
    teamId: "baystars",
    name: "マルセリーノ",
    nameKana: "まるせりーの",
    jerseyNumber: 98,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-01-01",
    birthPlace: "Dominican Republic",
    height: 188,
    weight: 90,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-74",
    teamId: "baystars",
    name: "フォード",
    nameKana: "ふぉーど",
    jerseyNumber: 99,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1998-01-01",
    birthPlace: "USA",
    height: 188,
    weight: 92,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-75",
    teamId: "baystars",
    name: "石上泰輝",
    nameKana: "いしがみたいき",
    jerseyNumber: 44,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-04-21",
    birthPlace: "神奈川",
    height: 175,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  // BayStars 育成選手
  {
    id: "baystars-76",
    teamId: "baystars",
    name: "草野陽斗",
    nameKana: "くさのはると",
    jerseyNumber: 101,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-77",
    teamId: "baystars",
    name: "清水麻成",
    nameKana: "しみずまなり",
    jerseyNumber: 102,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-78",
    teamId: "baystars",
    name: "金渕光希",
    nameKana: "かなぶちみつき",
    jerseyNumber: 103,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-79",
    teamId: "baystars",
    name: "今野瑠斗",
    nameKana: "こんのると",
    jerseyNumber: 108,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-80",
    teamId: "baystars",
    name: "吉岡暖",
    nameKana: "よしおかだん",
    jerseyNumber: 111,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-81",
    teamId: "baystars",
    name: "笠谷俊介",
    nameKana: "かさやしゅんすけ",
    jerseyNumber: 199,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2000-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-82",
    teamId: "baystars",
    name: "上甲凌大",
    nameKana: "じょうこうりょうた",
    jerseyNumber: 127,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-83",
    teamId: "baystars",
    name: "近藤大雅",
    nameKana: "こんどうたいが",
    jerseyNumber: 130,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-84",
    teamId: "baystars",
    name: "蓮",
    nameKana: "れん",
    jerseyNumber: 100,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2004-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-85",
    teamId: "baystars",
    name: "小笠原蒼",
    nameKana: "おがさわらあおい",
    jerseyNumber: 125,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-86",
    teamId: "baystars",
    name: "西巻賢二",
    nameKana: "にしまきけんじ",
    jerseyNumber: 129,
    position: "内野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1997-07-19",
    birthPlace: "宮城",
    height: 175,
    weight: 75,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-87",
    teamId: "baystars",
    name: "粟飯原龍之介",
    nameKana: "あいばらりゅうのすけ",
    jerseyNumber: 133,
    position: "内野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 178,
    weight: 74,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-88",
    teamId: "baystars",
    name: "高見澤郁魅",
    nameKana: "たかみざわふみ",
    jerseyNumber: 193,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2005-01-01",
    birthPlace: "神奈川",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },

  // Carp
  {
    id: "carp-1",
    teamId: "carp",
    name: "秋山翔吾",
    nameKana: "あきやましょうご",
    jerseyNumber: 31,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1988-04-16",
    birthPlace: "神奈川",
    height: 182,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-2",
    teamId: "carp",
    name: "西川龍馬",
    nameKana: "にしかわりょうま",
    jerseyNumber: 51,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-07-18",
    birthPlace: "鳥取",
    height: 178,
    weight: 84,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-3",
    teamId: "carp",
    name: "末包昇大",
    nameKana: "すえかねのぶひろ",
    jerseyNumber: 62,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-06-13",
    birthPlace: "広島",
    height: 185,
    weight: 95,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-4",
    teamId: "carp",
    name: "九里亜蓮",
    nameKana: "くりあれん",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-03-07",
    birthPlace: "鳥取",
    height: 181,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-5",
    teamId: "carp",
    name: "床田寛樹",
    nameKana: "とこだひろき",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-07-20",
    birthPlace: "広島",
    height: 182,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-6",
    teamId: "carp",
    name: "大瀬良大地",
    nameKana: "おおせらだいち",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-06-28",
    birthPlace: "長崎",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },

  // Dragons
  {
    id: "dragons-1",
    teamId: "dragons",
    name: "岡林勇希",
    nameKana: "おかばやしゆうき",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "2002-03-06",
    birthPlace: "愛知",
    height: 170,
    weight: 70,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-2",
    teamId: "dragons",
    name: "大島洋平",
    nameKana: "おおしまようへい",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1985-11-04",
    birthPlace: "静岡",
    height: 172,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-3",
    teamId: "dragons",
    name: "石川昂弥",
    nameKana: "いしかわたかや",
    jerseyNumber: 5,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-04",
    birthPlace: "愛知",
    height: 185,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-4",
    teamId: "dragons",
    name: "柳裕也",
    nameKana: "やなぎゆうや",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-22",
    birthPlace: "福岡",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-5",
    teamId: "dragons",
    name: "小笠原慎之介",
    nameKana: "おがさわらしんのすけ",
    jerseyNumber: 20,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-10-11",
    birthPlace: "神奈川",
    height: 183,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-6",
    teamId: "dragons",
    name: "涌井秀章",
    nameKana: "わくいひであき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1986-06-21",
    birthPlace: "埼玉",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },

  // Swallows
  {
    id: "swallows-1",
    teamId: "swallows",
    name: "村上宗隆",
    nameKana: "むらかみむねたか",
    jerseyNumber: 55,
    position: "三塁手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "2000-02-02",
    birthPlace: "熊本",
    height: 188,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-2",
    teamId: "swallows",
    name: "塩見泰隆",
    nameKana: "しおみやすたか",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-05-22",
    birthPlace: "鳥取",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-3",
    teamId: "swallows",
    name: "山田哲人",
    nameKana: "やまだてつと",
    jerseyNumber: 1,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-07-16",
    birthPlace: "大阪",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-4",
    teamId: "swallows",
    name: "小川泰弘",
    nameKana: "おがわやすひろ",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-07-26",
    birthPlace: "大阪",
    height: 168,
    weight: 71,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-5",
    teamId: "swallows",
    name: "石川雅規",
    nameKana: "いしかわまさのり",
    jerseyNumber: 19,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1981-01-30",
    birthPlace: "秋田",
    height: 167,
    weight: 68,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-6",
    teamId: "swallows",
    name: "高橋奎二",
    nameKana: "たかはしけいじ",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-11",
    birthPlace: "沖縄",
    height: 188,
    weight: 83,
    nationality: "日本",
    active: true,
  },
];
