export const playersCentral = [
  // Giants
  {
    id: "giants-1",
    teamId: "giants",
    name: "岡本和真",
    nameKana: "おかもとかずま",
    jerseyNumber: 25,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-06-30",
    birthPlace: "奈良",
    height: 185,
    weight: 93,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-2",
    teamId: "giants",
    name: "坂本勇人",
    nameKana: "さかもとはやと",
    jerseyNumber: 6,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1988-12-14",
    birthPlace: "兵庫",
    height: 180,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-3",
    teamId: "giants",
    name: "丸佳浩",
    nameKana: "まるよしひろ",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1989-04-11",
    birthPlace: "千葉",
    height: 178,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-4",
    teamId: "giants",
    name: "戸郷翔征",
    nameKana: "とごうしょうせい",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-10-09",
    birthPlace: "奈良",
    height: 183,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-5",
    teamId: "giants",
    name: "菅野智之",
    nameKana: "すがのともゆき",
    jerseyNumber: 18,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1989-10-11",
    birthPlace: "東京",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "giants-6",
    teamId: "giants",
    name: "高橋礼",
    nameKana: "たかはしれい",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "右" as const,
    throws: "両" as const,
    birthDate: "1995-08-09",
    birthPlace: "千葉",
    height: 186,
    weight: 95,
    nationality: "日本",
    active: true,
  },

  // Tigers
  {
    id: "tigers-1",
    teamId: "tigers",
    name: "大山悠輔",
    nameKana: "おおやまゆうすけ",
    jerseyNumber: 3,
    position: "一塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-19",
    birthPlace: "鳥取",
    height: 188,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-2",
    teamId: "tigers",
    name: "近本光司",
    nameKana: "ちかもとこうじ",
    jerseyNumber: 5,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-09",
    birthPlace: "兵庫",
    height: 175,
    weight: 75,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-3",
    teamId: "tigers",
    name: "木浪聖也",
    nameKana: "きなみせいや",
    jerseyNumber: 51,
    position: "遊撃手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1995-05-26",
    birthPlace: "石川",
    height: 174,
    weight: 72,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-4",
    teamId: "tigers",
    name: "青柳晃洋",
    nameKana: "あおやぎこうよう",
    jerseyNumber: 21,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-10-21",
    birthPlace: "兵庫",
    height: 180,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-5",
    teamId: "tigers",
    name: "西勇輝",
    nameKana: "にしゆうき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-11-10",
    birthPlace: "岡山",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "tigers-6",
    teamId: "tigers",
    name: "伊藤将司",
    nameKana: "いとうまさし",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-21",
    birthPlace: "千葉",
    height: 178,
    weight: 82,
    nationality: "日本",
    active: true,
  },

  // BayStars (2025年ロスター)
  {
    id: "baystars-1",
    teamId: "baystars",
    name: "牧秀悟",
    nameKana: "まきしゅうご",
    jerseyNumber: 2,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1998-04-02",
    birthPlace: "島根",
    height: 182,
    weight: 100,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-2",
    teamId: "baystars",
    name: "佐野恵太",
    nameKana: "さのけいた",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1994-11-28",
    birthPlace: "鳥取",
    height: 174,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-3",
    teamId: "baystars",
    name: "山本祐大",
    nameKana: "やまもとゆうだい",
    jerseyNumber: 50,
    position: "捕手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-03-25",
    birthPlace: "大阪",
    height: 174,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-4",
    teamId: "baystars",
    name: "東克樹",
    nameKana: "あずまかつき",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-11-18",
    birthPlace: "兵庫",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-5",
    teamId: "baystars",
    name: "宮崎敏郎",
    nameKana: "みやざきとしろう",
    jerseyNumber: 51,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1988-08-14",
    birthPlace: "大分",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-6",
    teamId: "baystars",
    name: "筒香嘉智",
    nameKana: "つつごうよしとも",
    jerseyNumber: 25,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "1991-11-26",
    birthPlace: "和歌山",
    height: 185,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-7",
    teamId: "baystars",
    name: "蝦名達夫",
    nameKana: "えびなたつお",
    jerseyNumber: 61,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-05-01",
    birthPlace: "北海道",
    height: 184,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-8",
    teamId: "baystars",
    name: "桑原将志",
    nameKana: "くわはらまさし",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-01-30",
    birthPlace: "広島",
    height: 180,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-9",
    teamId: "baystars",
    name: "神里和毅",
    nameKana: "かみさとかずき",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-04-06",
    birthPlace: "沖縄",
    height: 176,
    weight: 78,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-10",
    teamId: "baystars",
    name: "入江大生",
    nameKana: "いりえたいせい",
    jerseyNumber: 22,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1999-07-02",
    birthPlace: "神奈川",
    height: 184,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-11",
    teamId: "baystars",
    name: "伊勢大夢",
    nameKana: "いせひろむ",
    jerseyNumber: 13,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-04-20",
    birthPlace: "熊本",
    height: 175,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "baystars-12",
    teamId: "baystars",
    name: "アンドレ・ジャクソン",
    nameKana: "あんどれじゃくそん",
    jerseyNumber: 42,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1996-05-01",
    birthPlace: "California",
    height: 196,
    weight: 104,
    nationality: "外国",
    active: true,
  },
  {
    id: "baystars-13",
    teamId: "baystars",
    name: "ローワン・ウィック",
    nameKana: "ろーわんうぃっく",
    jerseyNumber: 95,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-11-09",
    birthPlace: "British Columbia",
    height: 196,
    weight: 100,
    nationality: "外国",
    active: true,
  },

  // Carp
  {
    id: "carp-1",
    teamId: "carp",
    name: "秋山翔吾",
    nameKana: "あきやましょうご",
    jerseyNumber: 31,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1988-04-16",
    birthPlace: "神奈川",
    height: 182,
    weight: 87,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-2",
    teamId: "carp",
    name: "西川龍馬",
    nameKana: "にしかわりょうま",
    jerseyNumber: 51,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1995-07-18",
    birthPlace: "鳥取",
    height: 178,
    weight: 84,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-3",
    teamId: "carp",
    name: "末包昇大",
    nameKana: "すえかねのぶひろ",
    jerseyNumber: 62,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1997-06-13",
    birthPlace: "広島",
    height: 185,
    weight: 95,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-4",
    teamId: "carp",
    name: "九里亜蓮",
    nameKana: "くりあれん",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-03-07",
    birthPlace: "鳥取",
    height: 181,
    weight: 86,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-5",
    teamId: "carp",
    name: "床田寛樹",
    nameKana: "とこだひろき",
    jerseyNumber: 29,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1996-07-20",
    birthPlace: "広島",
    height: 182,
    weight: 88,
    nationality: "日本",
    active: true,
  },
  {
    id: "carp-6",
    teamId: "carp",
    name: "大瀬良大地",
    nameKana: "おおせらだいち",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1991-06-28",
    birthPlace: "長崎",
    height: 180,
    weight: 86,
    nationality: "日本",
    active: true,
  },

  // Dragons
  {
    id: "dragons-1",
    teamId: "dragons",
    name: "岡林勇希",
    nameKana: "おかばやしゆうき",
    jerseyNumber: 7,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "2002-03-06",
    birthPlace: "愛知",
    height: 170,
    weight: 70,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-2",
    teamId: "dragons",
    name: "大島洋平",
    nameKana: "おおしまようへい",
    jerseyNumber: 1,
    position: "外野手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1985-11-04",
    birthPlace: "静岡",
    height: 172,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-3",
    teamId: "dragons",
    name: "石川昂弥",
    nameKana: "いしかわたかや",
    jerseyNumber: 5,
    position: "三塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "2002-01-04",
    birthPlace: "愛知",
    height: 185,
    weight: 96,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-4",
    teamId: "dragons",
    name: "柳裕也",
    nameKana: "やなぎゆうや",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-12-22",
    birthPlace: "福岡",
    height: 185,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-5",
    teamId: "dragons",
    name: "小笠原慎之介",
    nameKana: "おがさわらしんのすけ",
    jerseyNumber: 20,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-10-11",
    birthPlace: "神奈川",
    height: 183,
    weight: 85,
    nationality: "日本",
    active: true,
  },
  {
    id: "dragons-6",
    teamId: "dragons",
    name: "涌井秀章",
    nameKana: "わくいひであき",
    jerseyNumber: 14,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1986-06-21",
    birthPlace: "埼玉",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },

  // Swallows
  {
    id: "swallows-1",
    teamId: "swallows",
    name: "村上宗隆",
    nameKana: "むらかみむねたか",
    jerseyNumber: 55,
    position: "三塁手" as const,
    bats: "左" as const,
    throws: "右" as const,
    birthDate: "2000-02-02",
    birthPlace: "熊本",
    height: 188,
    weight: 97,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-2",
    teamId: "swallows",
    name: "塩見泰隆",
    nameKana: "しおみやすたか",
    jerseyNumber: 8,
    position: "外野手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1994-05-22",
    birthPlace: "鳥取",
    height: 182,
    weight: 90,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-3",
    teamId: "swallows",
    name: "山田哲人",
    nameKana: "やまだてつと",
    jerseyNumber: 1,
    position: "二塁手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1992-07-16",
    birthPlace: "大阪",
    height: 179,
    weight: 80,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-4",
    teamId: "swallows",
    name: "小川泰弘",
    nameKana: "おがわやすひろ",
    jerseyNumber: 11,
    position: "投手" as const,
    bats: "右" as const,
    throws: "右" as const,
    birthDate: "1990-07-26",
    birthPlace: "大阪",
    height: 168,
    weight: 71,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-5",
    teamId: "swallows",
    name: "石川雅規",
    nameKana: "いしかわまさのり",
    jerseyNumber: 19,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1981-01-30",
    birthPlace: "秋田",
    height: 167,
    weight: 68,
    nationality: "日本",
    active: true,
  },
  {
    id: "swallows-6",
    teamId: "swallows",
    name: "高橋奎二",
    nameKana: "たかはしけいじ",
    jerseyNumber: 17,
    position: "投手" as const,
    bats: "左" as const,
    throws: "左" as const,
    birthDate: "1997-07-11",
    birthPlace: "沖縄",
    height: 188,
    weight: 83,
    nationality: "日本",
    active: true,
  },
];
