export const standings: {
  seasonYear: number;
  teamId: string;
  league: string;
  rank: number;
  wins: number;
  losses: number;
  draws: number;
  winRate: number;
  gamesBehind: number;
  runsFor: number;
  runsAgainst: number;
}[] = [
  // --- Central League ---
  {
    seasonYear: 2024,
    teamId: "tigers",
    league: "セントラル",
    rank: 1,
    wins: 74,
    losses: 55,
    draws: 14,
    winRate: 0.574,
    gamesBehind: 0,
    runsFor: 571,
    runsAgainst: 488,
  },
  {
    seasonYear: 2024,
    teamId: "baystars",
    league: "セントラル",
    rank: 2,
    wins: 71,
    losses: 57,
    draws: 15,
    winRate: 0.555,
    gamesBehind: 2.5,
    runsFor: 558,
    runsAgainst: 497,
  },
  {
    seasonYear: 2024,
    teamId: "giants",
    league: "セントラル",
    rank: 3,
    wins: 68,
    losses: 58,
    draws: 17,
    winRate: 0.540,
    gamesBehind: 4.5,
    runsFor: 543,
    runsAgainst: 502,
  },
  {
    seasonYear: 2024,
    teamId: "carp",
    league: "セントラル",
    rank: 4,
    wins: 66,
    losses: 60,
    draws: 17,
    winRate: 0.524,
    gamesBehind: 6.5,
    runsFor: 522,
    runsAgainst: 510,
  },
  {
    seasonYear: 2024,
    teamId: "dragons",
    league: "セントラル",
    rank: 5,
    wins: 62,
    losses: 65,
    draws: 16,
    winRate: 0.488,
    gamesBehind: 11,
    runsFor: 487,
    runsAgainst: 521,
  },
  {
    seasonYear: 2024,
    teamId: "swallows",
    league: "セントラル",
    rank: 6,
    wins: 55,
    losses: 72,
    draws: 16,
    winRate: 0.433,
    gamesBehind: 18,
    runsFor: 448,
    runsAgainst: 574,
  },

  // --- Pacific League ---
  {
    seasonYear: 2024,
    teamId: "hawks",
    league: "パシフィック",
    rank: 1,
    wins: 80,
    losses: 49,
    draws: 14,
    winRate: 0.620,
    gamesBehind: 0,
    runsFor: 634,
    runsAgainst: 487,
  },
  {
    seasonYear: 2024,
    teamId: "marines",
    league: "パシフィック",
    rank: 2,
    wins: 70,
    losses: 57,
    draws: 16,
    winRate: 0.551,
    gamesBehind: 9,
    runsFor: 561,
    runsAgainst: 512,
  },
  {
    seasonYear: 2024,
    teamId: "eagles",
    league: "パシフィック",
    rank: 3,
    wins: 65,
    losses: 62,
    draws: 16,
    winRate: 0.512,
    gamesBehind: 14,
    runsFor: 524,
    runsAgainst: 531,
  },
  {
    seasonYear: 2024,
    teamId: "buffaloes",
    league: "パシフィック",
    rank: 4,
    wins: 62,
    losses: 65,
    draws: 16,
    winRate: 0.488,
    gamesBehind: 17,
    runsFor: 503,
    runsAgainst: 538,
  },
  {
    seasonYear: 2024,
    teamId: "lions",
    league: "パシフィック",
    rank: 5,
    wins: 55,
    losses: 73,
    draws: 15,
    winRate: 0.430,
    gamesBehind: 24.5,
    runsFor: 461,
    runsAgainst: 578,
  },
  {
    seasonYear: 2024,
    teamId: "fighters",
    league: "パシフィック",
    rank: 6,
    wins: 52,
    losses: 75,
    draws: 16,
    winRate: 0.409,
    gamesBehind: 27,
    runsFor: 443,
    runsAgainst: 592,
  },
];
