export const teams: {
  id: string;
  name: string;
  shortName: string;
  league: "セントラル" | "パシフィック";
  city: string;
  color: string;
  foundedYear: number;
  stadiumId: string;
}[] = [
  {
    id: "giants",
    name: "読売ジャイアンツ",
    shortName: "巨人",
    league: "セントラル",
    city: "東京",
    color: "#FF6600",
    foundedYear: 1934,
    stadiumId: "tokyo-dome",
  },
  {
    id: "tigers",
    name: "阪神タイガース",
    shortName: "阪神",
    league: "セントラル",
    city: "兵庫",
    color: "#FFE100",
    foundedYear: 1935,
    stadiumId: "hanshin-koshien",
  },
  {
    id: "baystars",
    name: "横浜DeNAベイスターズ",
    shortName: "DeNA",
    league: "セントラル",
    city: "神奈川",
    color: "#004B93",
    foundedYear: 1950,
    stadiumId: "yokohama-stadium",
  },
  {
    id: "carp",
    name: "広島東洋カープ",
    shortName: "広島",
    league: "セントラル",
    city: "広島",
    color: "#CC0000",
    foundedYear: 1950,
    stadiumId: "mazda-stadium",
  },
  {
    id: "dragons",
    name: "中日ドラゴンズ",
    shortName: "中日",
    league: "セントラル",
    city: "愛知",
    color: "#003087",
    foundedYear: 1936,
    stadiumId: "bantelink-nagoya",
  },
  {
    id: "swallows",
    name: "東京ヤクルトスワローズ",
    shortName: "ヤクルト",
    league: "セントラル",
    city: "東京",
    color: "#00A040",
    foundedYear: 1950,
    stadiumId: "jingu-stadium",
  },
  {
    id: "hawks",
    name: "福岡ソフトバンクホークス",
    shortName: "SB",
    league: "パシフィック",
    city: "福岡",
    color: "#F6D100",
    foundedYear: 1938,
    stadiumId: "fukuoka-paypay",
  },
  {
    id: "marines",
    name: "千葉ロッテマリーンズ",
    shortName: "ロッテ",
    league: "パシフィック",
    city: "千葉",
    color: "#000000",
    foundedYear: 1950,
    stadiumId: "zozo-marine",
  },
  {
    id: "eagles",
    name: "東北楽天ゴールデンイーグルス",
    shortName: "楽天",
    league: "パシフィック",
    city: "宮城",
    color: "#860019",
    foundedYear: 2005,
    stadiumId: "miyagi-baseball",
  },
  {
    id: "buffaloes",
    name: "オリックス・バファローズ",
    shortName: "Bs",
    league: "パシフィック",
    city: "大阪",
    color: "#0F2E7A",
    foundedYear: 2004,
    stadiumId: "kyocera-dome",
  },
  {
    id: "lions",
    name: "埼玉西武ライオンズ",
    shortName: "西武",
    league: "パシフィック",
    city: "埼玉",
    color: "#00568C",
    foundedYear: 1950,
    stadiumId: "belluna-dome",
  },
  {
    id: "fighters",
    name: "北海道日本ハムファイターズ",
    shortName: "日ハム",
    league: "パシフィック",
    city: "北海道",
    color: "#003D7D",
    foundedYear: 1946,
    stadiumId: "escon-field",
  },
];
